### ISSUE TITLE
miners go to containers

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#1002]
so when you put a container down where the miner is harvesting and then the miner dies the new miner will sometimes pick a new spot to harvest energy from. that is very annoying so maybe when you put the container down the miner harvests the energy from only that spot.

**Comment by chobobobo** [comment]
Have a look at creep.behaviour.miner inside the if statement that starts:
`if( !creep.data.determinatedSpot ) {`
that is where we decide what spot the miner will use.  It can be modified to prioritize a spot that has a container if it is free.

**Comment by SEATURTLEKING** [comment]
oh ok ty

**Comment by chobobobo** [comment]
Actually, if possible you should make a new branch eg `change/minersOnContainers` and then make the changes in that branch and submit a pull request(PR) to have them merged into `/dev`  I think this would be a good improvement to miners.

**Comment by SEATURTLEKING** [comment]
we can work on this together ( @Perrytheplatypus43 @chobobobo and me )

**Comment by SEATURTLEKING** [comment]
should not be to hard

**Comment by chobobobo** [comment]
wasn't too hard :) https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1030

**Comment by Spedwards** [comment]
Let's keep this open until the changes are merged, shall we?

**Comment by chobobobo** [comment]
Agreed, merged now.
