### ISSUE TITLE
eliminate the need for ROUTE_PRECALCULATION with traveler

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1006]
Need to investigate what benefit this is offering and see if it can be integrated, having to run with the hidden option ROUTE_PRECALCULATION=true is not reasonable.

**Comment by karlthepagan** [comment]
I would consider every difference between us and traveler API a bug at this point. We should get PR's in.

**Comment by karlthepagan** [comment]
Having a list of exits in a long route is very useful for combat situations. Each selected exit along this route represents a possible safe spot which I am making use of currently.

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/1143 is an instance of the reason it is enabled.

**Comment by chobobobo** [comment]
it seems like this happens when the border wall is 1 thick.. I will investigate that

**Comment by chobobobo** [comment]
resolved by https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1286
