### ISSUE TITLE
fix idle/avoid move cost matrices

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1007]
These were replaced when we started caching cost matrices, they had specific matrices for their purposes and should be reimplemented.  I heard you talking about this @karlthepagan ?

**Comment by karlthepagan** [comment]
yes, I'm not there yet, but I would like to see us cache threat positions and making a move/avoid algorithm eventually.

**Comment by karlthepagan** [comment]
when upgraders or miners arrive at their determinatedSpot they should register themselves as "structures" - or maybe as obstacles, but still they should be 0xFF in the structure matrix

also when construction sites are added cost matrixes need to update

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1089 addresses this issue

**Comment by chobobobo** [comment]
When creeps with determinatedSpots die, they need to invalidate the costMatrix using a callback.

**Comment by chobobobo** [comment]
resolved by 1089
