### ISSUE TITLE
Spawning Visual

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#1016]
you know when your spawn is spawning something and you look at the spawn info and it says how much time it has left of spawning something/how much time is needed to spawn.maybe a visual can appear next to the spawn displaying this info

**Comment by karlthepagan** [comment]
Mine looks like this:

![image](https://cloud.githubusercontent.com/assets/308745/24087986/7ff9eb4a-0ce2-11e7-83dc-7b7ffaaec1e5.png)

Are you seeing a problem with the spawn visual right now?

**Comment by SEATURTLEKING** [comment]
oh mine does not look like that. i guess i have to have the new version thank you for letting me know.
