### ISSUE TITLE
Defender Logic

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#1025]
Maybe the defenders can have some logic, like if one creep if doing most of the attacking then most of the defenders focus on it but some defenders need to make sure they stay back and attack the other attackers just because these defenders still can do some damage.

**Comment by Dasku** [comment]
This is getting into "squads" and group strategy I think. And any advanced military strategy should be discussed and developed internally.
