### ISSUE TITLE
Remote hauler will be assigned to a room with no spawn and get stuck

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#1048]
https://screeps.com/a/#!/history/E81N29?t=18243366

The hauler at the right is spamming "no action" messages.

The solution was to put a white/yellow "drop" flag next to the spawn.

A better hierarchy for dropping: drop at flag, or spawn, or spawn construction site, or controller.

Need to figure out if this is a problem for the release candidate.

**Comment by chobobobo** [comment]
resolved by #1078
