### ISSUE TITLE
Bulldozer sitting on construction site in Safe Mode room

### ISSUE THREAD

**Issue by mayson14** [ScreepsOCS/screeps.behaviour-action-pattern#1057]
worker creep stuck on non friendly construction site.. possibly due to room being in safe mode

![image](https://cloud.githubusercontent.com/assets/8452532/24326797/09f28650-1174-11e7-9117-bcb48bfecc3c.png)

**Comment by chobobobo** [comment]
I had a look at the room, and it's a spawn belonging to the previous inhabitant, possibly a screeps bug actually.

**Comment by mayson14** [comment]
update: old spawn construction site [seemingly] randomly disappeared.

**Comment by Spedwards** [comment]
The issue here appears to be a Screeps bug, not one on our end, but it does bring to light a possible outcome I did not think about.
