### ISSUE TITLE
Worker Doing Nothing

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#1070]
Getting reports from @Satriani1980 that his workers are idling. He says it's happening randomly (as in not every worker).

Trace:

```
[9:19:24 PM]18280342 Creep no WORK {"creepName":"worker-800-2","pos":{"x":24,"y":10,"roomName":"W73N89"},"Action":"repairing","Creep":"repairNearby"}
[9:19:24 PM]18280342 Creep run {"creepName":"worker-800-2","pos":{"x":24,"y":10,"roomName":"W73N89"},"Behaviour":"worker","Creep":"run"}
```

Last Action: `undefined`.  
Current Action: bulldozing

More information:

 - `creep.data.destiny` is undefined

**Comment by Spedwards** [comment]
There are no hostile construction sites in the room, so bulldozing should pass. However I don't think it's the problem. It doesn't seem to be running at all.

**Comment by Satriani1980** [comment]
Just did that, but doesn't seem to work.

**Comment by Satriani1980** [comment]
`Corrupt creep without population entry!! : worker-800-1`

This error I get now after reinstalling the latest dev version

**Comment by karlthepagan** [comment]
Corrupt creep is an unrelated persistent error. For workers it is not serious, they have the right balance of move/work/carry parts and will be auto-assigned to be workers.

**Comment by karlthepagan** [comment]
If a replay is available it may help us triage this.

**Comment by chobobobo** [comment]
@Satriani1980 is this still happening to you on current dev?

**Comment by Satriani1980** [comment]
@chobobobo I changed to the master. Then the problem disappeared.

**Comment by chobobobo** [comment]
upgraded to master or downgraded to master?

**Comment by Satriani1980** [comment]
I upgraded to master
