### ISSUE TITLE
Semi-auto construction: limited construction sites

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#1083]
I'm at 94 construction sites. If I play over 6 auto-build flags the CS creation fails but the flag is still removed.

IMO the flag should wait until there is a construction site underneath it which matches the flag's purpose before it gets removed. I don't trust the Screeps API 100% so I hesitate to trust the return value of the create command.

**Comment by Spedwards** [comment]
This shouldn't be happening...
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/blob/dev/room.js#L1442

**Comment by Spedwards** [comment]
I do have an idea for a hack-attempt to fix this, if the checks do not work.

**Comment by Spedwards** [comment]
Resolved in #1086
