### ISSUE TITLE
Event: Regenerate Costmatrix

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1084]
Make it possible for rooms to automatically regenerate their costMatrices based on a subscribed event.  Eg. Structures in the room have changed from tick to tick.

This is related to https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/1072

**Comment by karlthepagan** [comment]
<3

**Comment by chobobobo** [comment]
addressed by https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1087

**Comment by chobobobo** [comment]
merged.
