### ISSUE TITLE
Task.reputation.score can return 0 for a new player

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#1092]
This might be an order of operations problem / logical "race condition" (yes I know JS...) for new players.

It frequently surfaces as workers being stuck bulldozing.

**Comment by chobobobo** [comment]
score[mod.myName()] = CONST.MY_SCORE;
should that be .tolower?

**Comment by karlthepagan** [comment]
You may be right

**Comment by Spedwards** [comment]
Yeah, it seems everywhere else it's stored as lowercase. The correct change should be `setScore(mod.myName(), CONST.MY_SCORE);`
