### ISSUE TITLE
Potential memory issue with observers

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1106]
Could you help me to understand this?  I have 111 rooms now in my Memory.rooms and many are empty like this one:
![screen shot 2017-03-30 at 8 38 48 pm](https://cloud.githubusercontent.com/assets/25397533/24504481/0f3739b2-1589-11e7-8179-22b917ed558d.png)
![screen shot 2017-03-30 at 8 39 18 pm](https://cloud.githubusercontent.com/assets/25397533/24504484/106a2d30-1589-11e7-8f7b-eb0a3200360a.png)
what is this observers list used for, and why is it stored in that empty room?

**Comment by Spedwards** [comment]
Ahh... Forgot to re-add the `if (room.structures.observer)` check when I moved the method call.
