### ISSUE TITLE
Specify containers for different things using flags

### ISSUE THREAD

**Issue by torin555** [ScreepsOCS/screeps.behaviour-action-pattern#111]
What do you think of adding the ability to specify containers for different functions by placing a flag on top of it? For example, if you have a storage next to each source in the room, a large storage somewhere in the middle, and a storage next to the controller. 

Let's say you want the miners to deposit to the containers next to the sources (of course), you want the haulers to haul the energy from the first containers to the large storage container and the container next to the controller, as well as take energy from the large container to fill things like extensions when needed (workers would take from the large container as well). If you marked the source containers with let's say an orange-blue flag, the large central container with an orange-cyan flag, and the controller container with an orange green flag, it could mark those containers to be used in that way.

It could also be used to have multiple of each type, for example, multiple containers at the controller, or multiple central containers used for workers and haulers.

It would, of course, require checks for if you don't have a certain container, especially the middle containers, in which case haulers and workers would need to draw from the miner's containers as they do currently.

I like the idea of using flags for this because it allows for more control than doing it automatically based on position, since not every configuration can be foreseen.

**Comment by cyberblast** [comment]
Yes I thought about this option as well. But I discarded it, because I think the aim must be to use as much automation as possible (and ever growing). 
The script should sometimes be able to scan a new room, calculate its "threat" and possiblilities. Then maybe even claim that room and build all structures. And when you come back from your vacation you have 3 more rooms. ^^

**Comment by torin555** [comment]
Maybe a combo of the two? Like having the automatic system but being able to override it with the flags? Not having the flags makes sense if you just have the scripts build everything by themselves, but it isn't so great if you want to customize the rooms or if you take a room from someone else that already has things built

**Comment by cyberblast** [comment]
Feel free :) 
But I'm unsure if I want to merge that, because another goal is to keep things simple and small.  

You can have it in your branch. Or we open up a second branch right here, where we can put ALL new ideas and funtionality (e.g. drop mining as well). So we will then have a bare script and a fat script ;)  
And some functionality may be moved from fat to bare eventually later...  

What do you think?

**Comment by torin555** [comment]
Sounds fine, though I'm not entirely sure how to go about it, I'm not very good at working with containers. I can have a go though

**Comment by cyberblast** [comment]
hmm I'm thinking about it and how things may be merged once many features are combined in the "fat" version. 
Maybe better to create feature branches. I'll give it a try...

**Comment by torin555** [comment]
It may be good to make them modular options, with settings in the parameters tab, maybe by having separate files for opposing options, that way the features could be mixed and matched hopefully without issues

**Comment by cyberblast** [comment]
Ok, here you go: 
https://github.com/cyberblast/screeps.behaviour-action-pattern/tree/containerFlags 
simply create pull request against this branch. 

Hardest challenge will be to sync additions to the main branch (dev) down to the feature branches..

**Comment by cyberblast** [comment]
> It may be good to make them modular options, with settings in the parameters tab, maybe by having separate files for opposing options, that way the features could be mixed and matched hopefully without issues

Sounds good as well :+1:

**Comment by cyberblast** [comment]
Hmm I dont know if its possible, but if the whole feature fits into 1 file, without changing the other files, the module package would be fine. 
The code would need to 'virally' infect the other objects, overwriting their functions etc... 
e.g. behaviours/actions can be overwritten using the 'global' object.

**Comment by torin555** [comment]
That would be the best way to do it, the slightly more sloppy version would be that each file that needs to be different for a feature would have two versions, so for one feature you might be switching 3 different files.

**Comment by cyberblast** [comment]
Yes, but then it will be hard to combine different features. When there are two modules which both want to exchange the same file that will not be possible. well ... on the other hand if both overwrite the same fields/functions ( the viral way ) thats not better ^^

**Comment by torin555** [comment]
Yeah switching entire files would be less modular but probably easier to set up, while changing individual functions would be more modular but probably more complex to set up

**Comment by cyberblast** [comment]
I completed the dropmining as singlefile module. 
Its in the dropmining branch.

**Comment by torin555** [comment]
I should be able to start working on this once the container classification is set up and merged. At that point, all it should take is changing how the containers are classified if there's a certain flag on their location

**Comment by cyberblast** [comment]
Are you sure you want to implement this one? 
I don't think we really need it. At least not quite urgently. 
Of course you may focus on this one if you wish. It's completely up to you. 
But there is a growing list of bugs waiting for some attention...

**Comment by torin555** [comment]
That's why I put it on the Colony Behavior milestone ;)

**Comment by cyberblast** [comment]
ok. maybe it makes sense to remove the feature branch for this and create a new one when you are starting this one? You should have permissions for that.

**Comment by torin555** [comment]
Yeah sounds fine to me. I believe I do have the ability to create branches.
