### ISSUE TITLE
both master and dev branch causing cup to be either empty or maxed at all times

### ISSUE THREAD

**Issue by xXtheguy52Xx** [ScreepsOCS/screeps.behaviour-action-pattern#1115]

**Comment by xXtheguy52Xx** [comment]
CPU not cup

**Comment by karlthepagan** [comment]
Switching from canary to Dev is usually not stable. Try suiciding creeps to see if this improves.

**Comment by xXtheguy52Xx** [comment]
fixed itself? just needed some time i guess

**Comment by karlthepagan** [comment]
My bucket is suddenly empty. This might be server related or related to the number of active creeps.
