### ISSUE TITLE
[RC 0.7.0] Resolve 'incomplete path' messages

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1130]
We should either implement fixes that account for these incomplete paths being an inconsequential and normal part of execution, or investigate why they are happening and resolve them.  We can't have a release that's spewing warnings like this.

**Comment by karlthepagan** [comment]
With the current settings you won't get range undefined in this message. Perhaps output a new message when range = 0 saying that this creep's path is probably blocked.
