### ISSUE TITLE
Privateers stuck in room

### ISSUE THREAD

**Issue by Vykook** [ScreepsOCS/screeps.behaviour-action-pattern#1143]
I want rob some some minerals from my dead neighbour(what a shame), but privateers stuck in the wall. It seems that they choose shortest distance, but through the wall and not the shortest possible way(dotted line in screenshot). I'm on Canary branch. 
![privateers](https://cloud.githubusercontent.com/assets/873214/24598310/048079ba-184b-11e7-85e4-5c6423a1582f.png)

**Comment by chobobobo** [comment]
I believe this would have been resolved by #1286
