### ISSUE TITLE
Large body reservers try to go past 5000 ticks

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#1147]
This might be a general bug with reservation (and would affect privateer red/green and mining green/brown flag reserves) but I believe it is specific to the green/grey flag.

https://screeps.com/a/#!/history/E6N83?t=18436600 this room has a green/grey flag

**Comment by chobobobo** [comment]
I've actually been seeing this with green/brown flags from time to time as well

**Comment by chobobobo** [comment]
Yeah, it looks like anytime we lose visibility on the room, reservers spawn, that's one potential cause.
