### ISSUE TITLE
Critical Bucket Not Working

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#1161]
Something about the critical bucket level is not working, at all. I'm constantly below 50 bucket, and my average is barely above 300.

I'm not the only one having this issue either. Running 2017-04-04's canary build.

**Comment by Spedwards** [comment]
Possibly linked to #1179.

**Comment by chobobobo** [comment]
If the total usage of creeps in CRITICAL_ROLES or usage outside of those creeps is still above your CPU limit, this will happen, this is not a specific bug with critical bucket level, unless you propose implementing another, even stricter critical bucket level.
