### ISSUE TITLE
Investigate CPU Efficiency

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1214]
Here's a snapshot of ~ 800 ticks from the current canary, hauler, worker and labTech usage is up significantly above other creeps, and higher than 0.6.3, this is worth investigating.

Also, the claim.mining flag uses as much CPU as a miner, so if there's a quick fix to reduce that it would be beneficial.

![screen shot 2017-04-10 at 3 06 39 pm](https://cloud.githubusercontent.com/assets/25397533/24849730/aec43df8-1dff-11e7-9ef6-c1b36b9ff7dc.png)

**Comment by karlthepagan** [comment]
I think that while you've made some good strides in this department that we may need to stabilize the release and consider more drastic changes in 0.7.1

**Comment by chobobobo** [comment]
the behaviour refactor (https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1018) made great strides here
