### ISSUE TITLE
Creep.action.feeding.maxPerAction does not limit feeding.

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#1217]
I have been using `Creep.action.feeding.maxPerAction = 2` in my viral.mainInjection for my entire respawn but as you can see here my haulers are frequently all occupied by feeding.

https://screeps.com/a/#!/history/E7N84?t=18567950

**Comment by chobobobo** [comment]
yeah ```action.isAddableAction = function(creep){
    return true;
};``` will do that
