### ISSUE TITLE
Workers wont upgrade in invaded room if storage is present and has no energy.

### ISSUE THREAD

**Issue by OverlordQ** [ScreepsOCS/screeps.behaviour-action-pattern#1254]
Invaded a room that contained storage with the following contents:

https://i.imgur.com/yIaimod.png

The upgrade action never triggers.

Relevant code: https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/blob/dev/creep.action.upgrading.js#L5

Let's check the returns:

`return !creep.room.storage`

Returns false since there is storage.

`creep.room.storage.charge > 1`

Returns false since there is no energy

`(!creep.room.storage.my && creep.room.storage.store.energy > 0);`

Also returns false, since even though it's not my storage, it has no energy.

so `Creep.action.upgrading.isAddableAction` will always return false for this room unless I destroy the storage or otherwise manually intervene constantly.

**Comment by karlthepagan** [comment]
I believe the fix is to add `|| creep.room.rcl < 4` so that the room will upgrade to level 4 to build your own storage. Try it in a viral perhaps?

The problem of preserving the tens of thousands of credits locked away in that storage is out of scope for public OCS at this time.

**Comment by chobobobo** [comment]
This should have been resolved for upgraders by https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1269 but will be properly resolved by https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/1257
