### ISSUE TITLE
Check isActive on structures

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#1257]
We have a lot of checks to see if a structure exists, but we need to also add a check to see if the structure is active. Any rooms that downgrade, or are claimed after unclaiming will fail.

**Comment by chobobobo** [comment]
If you claim a room with storage already in it, but your RCL is too low for it to be active, it can cause bugs #1269 resolved issues for upgraders, but a more thorough check is needed to make sure our creeps only consider the storage when it's actually active.
