### ISSUE TITLE
find optimal position for controller's container.

### ISSUE THREAD

**Issue by mikiones** [ScreepsOCS/screeps.behaviour-action-pattern#126]
1. closest to sources and mining containers
2. in range of most upgraders.

**Comment by mikiones** [comment]
any additional requirements? ideas?

**Comment by cyberblast** [comment]
just try and see ;)

**Comment by cyberblast** [comment]
Commonly I'd say simply directly "in front" of it. near first spawn is ok. 
Only more interesting case is when its adjacent to a source. should be near to both then.

**Comment by mikiones** [comment]
not exactly as  there need to be clean path to refill container. assumed hauler will come from spawn general direction thats why upgraders go away from span: 
                  UUU
S----------CU
                 UUU

s spawn c container U spots for upgraders.

**Comment by cyberblast** [comment]
yes, but is this required? There should not be so many upgraders.. only 1 or 2.

**Comment by mikiones** [comment]
yes this upgraders gong to come from spawn so choosing spot between container and it blocking way for haulers.

**Comment by cyberblast** [comment]
Why not simply 'on' the container (same pos)?

**Comment by mikiones** [comment]
we going to have more then 1 upgrader first will sit on second will block again .
