### ISSUE TITLE
replacement remote miner has incomplete path

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1264]
When a remote miner arrives to replace its predecessor who has not yet died, it spits out a traveler incomplete path message.  Looking at the code, it should be trying to path to range 1 so I'm not certain why it is happening.

**Comment by karlthepagan** [comment]
Range 1 of the source? Only one field available?

**Comment by chobobobo** [comment]
Range 1 of the determinatedSpot, should look something like 
![screen shot 2017-04-15 at 11 19 59 am](https://cloud.githubusercontent.com/assets/25397533/25060352/94920f9c-21cd-11e7-9ebc-306149e9837c.png)

**Comment by chobobobo** [comment]
Ok, just discovered that creeps are not invalidating the costMatrix when they arrive at their determinatedSpot.. that's part of the issue..

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1265 is to resolve the issue of not invalidating when they arrive
