### ISSUE TITLE
healing action prevents border guard from defending both rooms

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#1315]
center room invaders are ruining my day

https://screeps.com/a/#!/history/E5N85?t=18740200

I'm going to look into a quick fix for 0.7.0 - this might be an internalViral

**Comment by chobobobo** [comment]
Was this resolved by #1319 ?

**Comment by karlthepagan** [comment]
Yes. I need to add the filter code into tutorial / internal.

**Comment by karlthepagan** [comment]
Will be resolved with internal changes. I highly recommend others writing your own viral (as I do) if you want to get finer control like aggressively avoiding moving away from the guard position in different scenarios.

**Comment by karlthepagan** [comment]
Internal was merged.
