### ISSUE TITLE
Storage inactive block

### ISSUE THREAD

**Issue by Almaravarion** [ScreepsOCS/screeps.behaviour-action-pattern#1317]
Add 'isActive' check wherever checking for storage; If a room cannot use storage creeps will still act as if it is active and working, despite RCL of the room being too low.

Example of room issue on recovered room 
https://screeps.com/a/#!/history/W67S88?t=18743270

After storage removal everything went back to normal;

**Comment by Spedwards** [comment]
Duplicate of #1257.
