### ISSUE TITLE
structure.isActive is actually an expensive call

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#1333]
While doing some profiling on action.feeding, I discovered that it nearly doubled the average usage of haulers and labTechs because of the cost of checking isActive on all spawns and extensions.
http://support.screeps.com/hc/en-us/community/posts/206611209-Structure-isActive-Absurdly-CPU-intensive references this issue, and @artem suggests caching.

My first thought is that we could check isActive once, and only update it when RCL changes.

**Comment by Spedwards** [comment]
We can have a new event, `Room.RCLChange` (might as well add `Game.GCLChange` as well). On that trigger:

```javascript
room.structures.all.forEach(s => {
    Util.set(room.memory, ['structures', 'active', s.id], s.isActive());
});
```

And add property:

```javascript
Object.defineProperty(Structure.prototype, 'active', {
    configurable: true,
    get() {
        return Util.get(this.room.memory, ['structures', 'active', s.id], s.isActive());
    }
});
```
