### ISSUE TITLE
Extensions aren't being added to memory on their own

### ISSUE THREAD

**Issue by torin555** [ScreepsOCS/screeps.behaviour-action-pattern#1339]
*As discussed on Slack*

Hmm, interesting little bug. When I build new extensions it's not adding them to memory. I've been having to delete my room memory and have it recreated to get my new extensions to work. Any idea why that might be happening?

**Comment by chobobobo** [comment]
It's entirely possible that we are not updating the in-memory cache when new extensions are constructed, need to investigate a good way to do this.
