### ISSUE TITLE
Auto Construction

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#17]
**Roads**
- get path between spawn/source/controller & put sites
- save established connections to mem
- check periodically (1000 ticks? slowing down?)
- set all fields range 1 & 2 around sources & controller to roads
- set road:  x+y%4 == 0 || x-y%4==0 => lighter checkers

**Comment by cyberblast** [comment]
What about auto setting extensions. 
- For each source.
- For each field with distance x (minimum range to source + next if belt fully build) around source. 
- When x + y % 2 == 0 (checkers) set Extension site. Else road. 
- After first scan set all inner fields for roads (checkers)

**Comment by cyberblast** [comment]
__Spawn__
* Try to calculate mid point between Sources & Controller
* if it's a wall check concentric
* target should also have no adjacent wall (including diagonal)

**Comment by cyberblast** [comment]
__Towers__
* Check concentric around spawn for a free field

**Comment by Dasku** [comment]
Internal issue # 23
