### ISSUE TITLE
reduce mineralMiner Size when Mineral source nearly empty

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#236]
at a harvesting lifetime of (nearly) 1500 ticks how many minerals will be harvested by each workpart (respecting extractor cooldown)? 
how many workParts would be required to fully harvest the remaining mineral? 

calc maxMulti depending on remaining mineral. 

e.g. like: min(11, ceil(multiToHarvestComplete))  (where 11 would be the max possible maxMulti (to stay below 50 parts))

**Comment by Dasku** [comment]
I got home from work today and neither of my 2 rooms with terminals have mineral miners at the mineral. Any ideas? (They both spawned 1 when I put on the new code, I watched it before I went to work)

**Comment by cyberblast** [comment]
Is there mineral available? I mean its sometimes depleted and takes some thousand ticks until its back there again... Then there will also be no mineralMiner...

**Comment by Dasku** [comment]
Both empty! Ha. Cheers!
