### ISSUE TITLE
destroy flag should override other invading targets

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#250]
There are circumstances (or always?), where the destroy flag doesn't work. 
also see report in #249

**Comment by Gestic** [comment]
dunno, this worked for me a few weeks ago as to what op did to walls while attacking without dismantleing. i found that if  you place the red flag the creeps just bump into walls/ramps. i had to place yellow flag in base then orange flags work. this workaround was done and verified a couple weeks ago may not work in current dev as it was innefective today. i will test further when i get the next chance

**Comment by cyberblast** [comment]
I'm also unsure about it, as it is working in general. The "problem" is that all creeps already have an other target assigned (due to the red/red flag). 

A possible change could be: 
As soon as an orange flag is placed in a room with a red/red flag, all targets by all (combat) creeps will be invalidated and a structure marked with an orange flag will become the new target. 

Would that be desireable?

**Comment by Gestic** [comment]
Yes orange flag should get struct priority over creeps because i can always change the order of the if target loop in the invading module right?

**Comment by cyberblast** [comment]
Ok, but I think it's more a change than a bug. 

Yes there needs to be a check in "invading" if the current target is a flagged one or if there is a flagged target available in that room.
