### ISSUE TITLE
Transitioning from lvl 2 to 3

### ISSUE THREAD

**Issue by forkmantis** [ScreepsOCS/screeps.behaviour-action-pattern#262]
The transition was is pretty slow.  After the first miner spawned, he could not mine fast enough to keep my workers full, so many of them were sitting around idle.  Maybe have the other workers continue to harvest from the 2nd source if there is not a miner on that source?  Or maybe re-assign a worker to temporarily act as a 2nd miner until a real one can be spawned?

**Comment by cyberblast** [comment]
I understand the problem, but its a one time transition. Such additional checks/logik would always be executed. I'm unsure if its worth the cpu...

**Comment by forkmantis** [comment]
OK.  I may test some stuff in my fork and see if it justifies the extra CPU or not.  If so, I'll create a pull request.

**Comment by cyberblast** [comment]
ok, great

**Comment by Dasku** [comment]
Currently workers stop mining when miners spawn, couldn't you just turn that off? If a worker has a valid location it can mine from, and has nothing else to do, shouldn't mining still be a valid job? mining > idle right? :D

**Comment by cyberblast** [comment]
Yeah, but the idea is to have dedicated miners. And each dedicated miner will mine one source completely empty. It fits exactly with 5 WORK parts. 
Thus workers will give this role completely away to the miners. 

Hmm. but it could be only disallowed for sources having a dedicated miner.. 
But I can't test it very well currently.

**Comment by cyberblast** [comment]
Could you please check if 723f432 works as desired?

**Comment by forkmantis** [comment]
Seemed to work pretty good to me.  Not only did it help when I was waiting on the second miner to spawn, but also when there is a gap between a dying miner and his/her replacement.
