### ISSUE TITLE
New Type: Scout

### ISSUE THREAD

**Issue by torin555** [ScreepsOCS/screeps.behaviour-action-pattern#276]
A new creep type called a scout which consists of only move parts (Maybe some tough parts as well). Its movement would be controlled entirely by a flag, and it could be used for testing enemy defense code or wasting the enemies resources like tower energy. 

When the scout died, its flag would be removed to avoid accidentally spawning more scouts. Each scout would be assigned to the flag that spawned it and moves using that flag to allow for multiple scouts doing different things at once. Thoughts?

**Comment by Dasku** [comment]
I like the idea for testing defences but I guess you could just spawn a small ranger or melee? As for draining towers I think it might be a bit more complicated as you need to out heal the damage of the tower(s). I think there is a couple discussions about this in other threads. #242 #205 #75

**Comment by torin555** [comment]
This would allow for much more precise control than just spawning a small ranger or melee. At the moment there's very little control over the movement of combat creeps and it wouldn't allow for separate movement from other combat creeps.

**Comment by cyberblast** [comment]
I think this is whats meant with #75 Teaser creeps. 
Move into enemy rooms, check tower behaviour, try to drain them etc... 

I'm unsure about the final behaviour. A flag system is one option. 
But it could also be part of a common invasion strategy and process. without the need to put a lot of different flags (invasion flag + 'scouting flag' + wall destroy flag + etc...), but just 1 to start the whole process.

**Comment by torin555** [comment]
Hmm, if you think it's a duplicate alright, but this is a much more advanced idea than that issue.

**Comment by cyberblast** [comment]
yes, you also didn't have do delete it. ;)
Best would be do post ideas to details on how such a creep should be used or behave into the original post...

**Comment by Gestic** [comment]
lol i made a post of an idea similar to this.. guess i should read the posts 👎 #278

**Comment by cyberblast** [comment]
no problem. 
just please try to have an eye on it ;) 

your posts are still referenced in the one kept open...
