### ISSUE TITLE
Hopper Creep ?

### ISSUE THREAD

**Issue by Gestic** [ScreepsOCS/screeps.behaviour-action-pattern#278]
One of my favourite parts of this game is the strategy and tactics of invading and defending. 

The hopper creep can function in both roles. As i've seen to date, it is the most scalable through RC lvls in terms of energy draining enemy bases which is a large part of efficiently sieging and invading.  

Why send zergs of creeps when you can just drain the towers or if his script is insufficient, even attack them. Or attacking walls without being cut down. 

Another use would be their ability to trigger advanced script events at certain key passages for enemy movements for example. Another use may be for bait and run or hit and run tactics.

The main thing this creep does is use mechanics such as how room borders work and how the game auto moves creeps when they attack or get attacked at these points. Also for determining enemy movements by sitting and watching room borders as efficient early warning or script triggering to send attackers or defenders before they get to certain points. May also be used for active energy denial by killing their privateers for example.

If implemented in current design i would designate a major flag color for the hopper creep and a minor color for the type of hopper.

Here is sample of very basic but working prototype code made by FaceWound. Thanks Pal!
(he says he's working on better less hackish code)

[Link to Hopper code in Pastebin](http://pastebin.com/yRpvc4Xf)

**Comment by cyberblast** [comment]
uhm. sorry, what exactly is a hopper creep again?

**Comment by Gestic** [comment]
a creep that hops between borders

**Comment by cyberblast** [comment]
-.- 

yes but thats the #75 Teaser creep, no?
