### ISSUE TITLE
Allow upgraders to take energy from Storage

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#279]
This could save links if you put your storage near your controller. 

May need a check to stop taking energy if it drops below a set value.

**Comment by Dasku** [comment]
As upgraders can reach quite far, may need to make it so the storage registers within 4 squares?

**Comment by cyberblast** [comment]
yes. just like containers and links

**Comment by Dasku** [comment]
Ok, so also need to ensure no conflict if the link and storage are in range, the link should become the centre link not the controller link.

**Comment by cyberblast** [comment]
Agreed. If there is a storage in range nearby containers and links should simply be ignored by the upgrader

**Comment by erik-smit** [comment]
> If there is a storage in range nearby containers and links should simply be ignored by the upgrader. => rated as "not in range of the controller"

How would this be implemented?

The upgrader doesn't decide if something is in range of the controller.
The room decides if something is in range of the controller by filling containerController and linksController 
and the upgrader uses this room-data to determine a spot to stand.

Should a storageController be added, maybe and the upgrader-logic changed to prefer the storageController if it exists?

**Comment by cyberblast** [comment]
I guess the simplest approach would be to adjust the room logic for containerController and linksController and keep them empty. 
A quick and dirty approach could be to simply add the storage as containerController. 
A clean approach would maybe require to add something like storageController, but would make it more complicated than necessary. 
While I'm unsure which one is more ugly ;) but both should work. 
Whats your opinion?

**Comment by Dasku** [comment]
If we just added the storage to containerController, would that mean the upgrader would still prioritise the link over the storage if they are both within range? 

This may not even matter thinking about it, however the workers/haulers would need to know the link is a storage link and not a controller link?

**Comment by cyberblast** [comment]
No, the upgrader would only get the storage as source then.

**Comment by Dasku** [comment]
Seems like this could be an easy fix then. I'll take a look when I get home, I may be able to sort this one.

**Comment by erik-smit** [comment]
Instead of adding a storageController, that would need to be added to the current linksController&containerController, how about creating a controllerSource, and adding storage, links and containers in the vicinity of the controller to that and using that for the upgrader replacing the current logic?

**Comment by cyberblast** [comment]
possible

**Comment by Dasku** [comment]
Ok maybe not as simple as I imagined. 

I don't have a storage near a controller yet so I'm not getting errors but here's what I tried. 

    'containerController': {
                configurable: true,
                get: function() {
                    if( _.isUndefined(this._containerController) ){  //finds anything undefined
                        let byType = c => c.controller == true; // container.controller = true? in range of controller?
                        this._containerController = _.filter(this.container, byType); // filters for containers, 
                    }
                    return this._containerController; //define as containerController
                }
            },

So I figured to add storage we filter for it like:
this._containerController = _.filter((this.container || this.storage), byType);

But without an error I'm unsure if this has worked (or even close to correct). 

I don't get c.controller == true. I'd expect this to be "If within range of controller = true. 

Maybe I should stick to learning for the time being! :D

**Comment by erik-smit** [comment]
> So I figured to add storage we filter for it like:
> this._containerController = _.filter((this.container || this.storage), byType);
> 
> But without an error I'm unsure if this has worked (or even close to correct).

I think the first argument of _.filter is an array, so you'll have to concatenate this.container and this.storage.

Maybe ``` this._containerController = _.filter(this.container.concat(this.storage), byType);``` but maybe this is too ugly code.

> I don't get c.controller == true. I'd expect this to be "If within range of controller = true.

This checks if the key 'controller' is set to true inside the filtered object.
I can't find it, but I believe it gets set somewhere if it's in range of the controller.

**Comment by cyberblast** [comment]
> I guess the simplest approach to exclude containers & links would be to adjust the room logic for containerController and linksController and keep them empty. 

containerController:
if storage in range to controller 
containerController = [storage];
else ... as before


linkController:
if storage in range to controller 
linkController = [];
else ... as before

**Comment by Dasku** [comment]
Wouldn't that over right it in the rooms I don't have a storage near the controller?

**Comment by erik-smit** [comment]
> containerController:
> if storage in range to controller 
> containerController = [storage];
> else ... as before

something like this?
```
this._containerController = 
    this.storage.controller ? [this.storage] : _.filter(this.container, byType);
```

**Comment by erik-smit** [comment]
I mean 

```
this._containerController = 
    this.storage && this.storage.controller ? [this.storage] : _.filter(this.container, byType);
```

Otherwise, you'd get undefined blah error when there's no storage, right?

**Comment by Dasku** [comment]
I got an email about a message in Slack but I can't respond to that at work, I've not given up, just didnt want to stop other people fixing if they could.

What you said above looks like it could work, the way I went is below, but again I wasnt sure if it was correct I was going to post in slack when I got home. (I cant test code at work, only view Github).

    'containerController': { 
                 configurable: true, 
                 get: function() { 
                     if( _.isUndefined(this._containerController) ){  
                         let byType = c => c.controller == true; 
                         this._containerController = _.filter(this.storage, byType); 
			         else {  
                         let byType = c => c.controller == true; 
                         this._containerController = _.filter(this.container, byType); 
                     } 
                     return this._containerController; 
                 } 
             },    



However, your code looks like a much more compact/clean way of coding the same thing? (The way I'm learning to code at the moment everything is long hand, I think I understand your code as  
"condition ? value-if-true : value-if-false
? = then
: = else"

**Comment by erik-smit** [comment]
> What you said above looks like it could work, the way I went is below, but again I wasnt sure if it was correct 

Your code is not correct, I think.
if this._containerController is not defined, set it to storage?
if this._containerController is defined, set it to container?

The _.isUndefined(this._containerController) is used as a form of caching.
So, when containerController is requested, it'll only need to calculcate it once.

> The way I'm learning to code at the moment everything is long hand, I think I understand your code as
> 
> "condition ? value-if-true : value-if-false
> ? = then
> : = else"

Correct, this is called a ternary.

**Comment by cyberblast** [comment]
```
this._containerController = 
    this.storage && this.storage.controller ? [this.storage] : _.filter(this.container, byType);
```
```
this._linksController = 
    this.storage && this.storage.controller ? [] : this.links.filter(byType);
```

looking good :)

**Comment by Dasku** [comment]
Thanks for your replies about this, maybe this is a bit beyond me at the moment, I haven't really used filtering in my JS course yet.  How my code worked in my head is not:
> if this._containerController is not defined, set it to storage?
> if this._containerController is defined, set it to container?

its more: 

    'containerController': { 
    configurable: true, 
    get: function() { 
     if( _.isUndefined(this._containerController) ){  // Collect all undefined objects in the room, call it this._containerController if its used 
     let byType = c => c.controller == true;  // find ones with c.controller meaning its within range of controller
     this._containerController = _.filter(this.storage, byType); // this._containerController = filter all storages, bytype leaving only one in the array which is close to the controller (there is only ever 1 though so this is redundant I guess)
     } else {  // else do what we did before, filtering containers instaed.
     let byType = c => c.controller == true; 
     this._containerController = _.filter(this.container, byType); 
     } 
     return this._containerController; 
    }, 


Reading your code it also makes sense in my head, I guess I just don't know enough yet to see this type of error.

    this._containerController = 
    this.storage && this.storage.controller ? [this.storage] : _.filter(this.container, byType);

If (its a storage & in range of controller) then set storage as the this._containerController :else: filter all containers by type and select the one near the controller. 

Anyway thanks for the comments it's a massive help for me, I'm just a bit concious of asking endless questions here taking up your guys time. I'll keep at my course in the hopes this will all one day become clear :D

**Comment by erik-smit** [comment]
` if( _.isUndefined(this._containerController) ){`

This is not "Collect all undefined objects in the room, call it this._containerController if its used".

This is "if this._containerController is not defined"

For reference, I think `if(!this._containerController){` would be the same.

> If (its a storage & in range of controller) then set storage as the this._containerController :else: filter all containers by type and select the one near the controller.

if this.storage is defined && this.storage.controller is defined then:

> I'm just a bit concious of asking endless questions here taking up your guys time.

Don't worry about it. I've enjoyed explaining this.

**Comment by Dasku** [comment]
Cheers, its making more sense now. My questions were actually going to be around the underscores, I've heard of lodash but know very little, I thought it was used for maths and filters, and its a JS module or library you can use, and screeps has it installed so we can use it without having to import it in every file? Not really sure what it does adds though in terms of functionality.

Also why is _container used and not just container? (this._containerController)

**Comment by cyberblast** [comment]
room.container would be the property we are actually implementing.  
room._container is surely not in use. 
so we use room._container to load a value (once if null/undefined) and to cache it (for during the current loop). 
And we will access it with room.container. 
just as example...

**Comment by erik-smit** [comment]
>  I've heard of lodash but know very little, I thought it was used for maths and filters, and its a JS module 
> or library you can use, and screeps has it installed so we can use it without having to import it in every file

Right.
