### ISSUE TITLE
Early RCL 6 allows colony to die?

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#283]
A few days ago when my first room reached RCL 6 I came home from work to find the colony dead. I sent a pioneer and restarted it and everything has been fine since. 

Couple days later my 2nd room reached RCL 6 and had no issues.

Around 6am this morning my 3rd room reached RCL 6, and just now I checked on my phone and the colony was dead here too. I've sent a pioneer to get it back on track.

As it happened a second time I wanted to check if anyone else has had a similar experience?

The only similarity I have noticed is that both times it happened, the colony died just before completing the build of the terminal (was between 50-75% complete in both rooms when colony died) - not sure if this is relevant though.

**Comment by Dasku** [comment]
I think I may have figured this out. I change my additional upgrader to spawn with 50K surplus, not 100k. Could this mean it drained my energy from storage to the point spawning stuff became lower and lower priority until everything died? I just got home and in my room there is 2 miners, a mineral miner and 1 worker. No haulers. But my storage only has 7k energy (as the pioneer that came is using storage energy to build the terminal - not filling the storage from links etc) Makes me think this could persist until the terminal is finished and energy builds back up to 100k (RCL6)

**Comment by erik-smit** [comment]
Do you already have your upgraders withdrawing from your storage?

Also, it seems like the workers have 'building' preferred over 'feeding' the spawn and extensions.
I think this could be related.

**Comment by Dasku** [comment]
Nope, my controller has a link for upgraders but none are spawned right now.

**Comment by Dasku** [comment]
I also cannot spawn a hauler with Game.spawns['Spawn2'].createCreepBySetup(Creep.setup.hauler)

Full spawn and extensions and no creeps spawing and still wont spawn one.

**Comment by erik-smit** [comment]
Creep.setup.hauler.maxCount(Game.spawns['Spawn2'].room) ?

**Comment by Dasku** [comment]
1
and one just spawned

**Comment by erik-smit** [comment]
Maybe you didn't have miners? I think the hauler maxCount is linked to miners.

**Comment by Dasku** [comment]
But I also lowered my MIN_ENERGY_STORAGE to 1000 temporarily

**Comment by Dasku** [comment]
2 miners and 1 mineral miner spawned atm (W53N11)

**Comment by Dasku** [comment]
I'm pretty sure its the MIN ENERGY storage, I think I recall cyber saying when you are below, it cuts down on spawns until its back over that amount.

**Comment by erik-smit** [comment]
```
            'conserveForDefense': {
                configurable: true,
                get: function () {
                    return (this.storage && this.storage.store.energy < MIN_STORAGE_ENERGY[this.controller.level]); 
                }
            },
```

`conserveForDefense` is used in creep.action.withdrawing, creep.behaviour.hauler.

Anyhow, I've got a room nearing RCL 6 so I'll keep an eye on it.

**Comment by forkmantis** [comment]
I had this issue as well.  I think I noticed that my haulers were spending all their time picking the dropped minerals, since the terminal had not been created yet.  As an experiment, I've made it so they won't pick minerals unless the amount is >= than their carryCapacity, hoping that they'll have time to refill extensions in between.

**Comment by cyberblast** [comment]
>  I've made it so they won't pick minerals unless the amount is >= than their carryCapacity 

sounds like a good idea.

**Comment by cyberblast** [comment]
When below MIN no upgrader will spawn. 
The hauler has no direct dependency to that MIN threshold, but on upgrader maxcount. 
Thats the problem.

**Comment by cyberblast** [comment]
I hope this was the only cause for that to happen. 
All of us should keep an eye on it...

**Comment by dkluempers** [comment]
I just had this happen to me.

**Comment by cyberblast** [comment]
@dkluempers did you use the latest code 325f69d500b286ac959838d96151c887ea551b90 from yesterday? you should send some pioneers to get it up again

**Comment by erik-smit** [comment]
> Anyhow, I've got a room nearing RCL 6 so I'll keep an eye on it.

FYI, I've noticed no issues.

Did you guys build the new extensions, terminal and extractor immediately?
I waited between them.

**Comment by Dasku** [comment]
I usually build everything as soon as I can. Which I think is my energy store drops so much leading to the colony dip. The always 1 hauler should fix this though.

**Comment by dkluempers** [comment]
I built the new extensions, lab, strorage then terminal.  It died when I was building the terminal.  I have been using the dev branch of the code - is that right one?  Not sure how to send pioneers for that one.

**Comment by dkluempers** [comment]
I do have the latest code is appears.  Nothing at all is spawning in the room

**Comment by erik-smit** [comment]
> Not sure how to send pioneers for that one.

You can send pioneers with a white/red flag.

https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/wiki/Flags

**Comment by dkluempers** [comment]
Sorry, I missed that.  I just set one

**Comment by dkluempers** [comment]
Erik - you are a steely eyed OCS screeps man :)

**Comment by dkluempers** [comment]
It spawns miners, workers, haulers but no upgrader

**Comment by erik-smit** [comment]
> Erik - you are a steely eyed OCS screeps man :)

How so?

**Comment by cyberblast** [comment]
> It spawns miners, workers, haulers but no upgrader 

It's intended to not spawn upgraders until MIN_STORAGE_ENERGY is reached.

**Comment by dkluempers** [comment]
It did finally do it.  I will take a look at that code.  Thanks
