### ISSUE TITLE
Enhancement: Avoid Room Flag

### ISSUE THREAD

**Issue by TafThorne** [ScreepsOCS/screeps.behaviour-action-pattern#300]
It would be helpful to have a flag for avoiding a room.  You might have agreed to avoid it with a another player.  It might be full of a aggressive other players troups or it might have a large number of spawn keepers in it.  The idea would be that creep routing attempts to avoid the room if it can find another route.  

Case in point for me: 
![image](https://cloud.githubusercontent.com/assets/586550/21232327/15a3e37a-c2e3-11e6-9a52-85ba27f49b4c.png)

The top right room of mine (pink logo) is not yet complete.  I need a few more worker units to reach there and finish the spawn.  I agreed a 2000 tick window with the black, yellow and white logo player for my units to reach that room.  During that time the turrets and defender in his room would ignore all my units, after that they get attacked.  There is a circuitous route available which would avoid all of his rooms and allow me to complete the build.  

This might also be helpful when massing units for an invasion.  You could place some guards on the far side of a target room and have them avoid passing through the target room initially.

**Comment by cyberblast** [comment]
Hi TafThorne, 
yes I absolutely agree, that we need that feature. 

We should also think about not using a flag but to have a list of 'forbidden' rooms in memory (-> flags will get a max usage limit eventually). 

The harder question is how to teach the creeps to avoid those creeps. 
There is a map route calculation implemented, where this could easily be added. Unfortunately it's not working reliable (the whole map route precalculation). It will give "NO PATH" errors in some cases. 

You could have a look into it: 
* Route precalculation gets activated by setting ROUTE_PRECALCULATION to true. 
* Pathfinding and calling route precalculation is in Creep.prototype.getPath in creep.js
* Route precalculation is implemented in Room.prototype.findRoute in room.js

Room avoidance would be achieved by returning Infinity in roomCallback in Game.map.findRoute. 

Another solution would be by utilizing the PathFinder...

**Comment by TafThorne** [comment]
> Room avoidance would be achieved by returning Infinity in roomCallback in Game.map.findRoute.

We might want to record an avoid and a never enter separately.  Returning some multiple of the found path length for avoided rooms and infinity for the forbidden rooms.

**Comment by karlthepagan** [comment]
Partially implemented in #454 - this helps the case of creeps spawning in rooms unsuitable for their destiny.

Still needs pathfinding work.

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/665 will resolve this issue by allowing you to set costs as below: 
ROUTE_PRECALCULATION: true, 
ROUTE_ROOM_COST: {}, // custom room routing cost: e.g. `{ 'W4N4': 11 }`. Affects bestSpawnRoomFor, Creep.Setup calculations, and travel cost predictions. Please call 'delete Memory.routeRange;' whenever you change this property.

**Comment by karlthepagan** [comment]
This is getting very close to completion with #665

**Comment by chobobobo** [comment]
The current way of doing this (0.7.0+) is to set Memory.rooms[roomName].hostile = true, ysing ROUTE_PRECALCULATION in combination with ROUTE_ROOM_COST will give you more fine-tuned avoidance by setting a preference for other rooms rather than blacklisting them.
