### ISSUE TITLE
Utilize Labs

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#31]
Requires some minerals...

**Comment by mikiones** [comment]
once you merge #176 i can fork for this one on top of it

**Comment by cyberblast** [comment]
We should not try to implement as much as possible and as fast as possible. I'd really prefer to ensure quality first. Are all those expressions and formulas right or are there better ways? 
Give it some time...

**Comment by mikiones** [comment]
quality comes from fixing bugs and problems in futures. not by avoiding them

**Comment by cyberblast** [comment]
Ok, no problem. just try to keep an eye on it ;) 

Sorry, I still couldn't manage to have a look into those PR's...

**Comment by mikiones** [comment]
anyway i need lab implementation for my base. so going to work on it now. once you ready with #28 i'll extract it as pr there

**Comment by mikiones** [comment]
probably going to cache ids in memory group them by 3 in distance 3 of each another as lab-set and array of those to room object.

each lab-set will have 2 inputs and 1 output

new action supply, will go over each of those and ask for required indigrands, if present in store,
the withdraw will be called for equal amount of integrands (100 H, 100 O) f.e and delivered to them.

each tick call runReaction if have enough resources. deliver output back to storage. ( once we have worth delivering about)

**Comment by mikiones** [comment]
so action Supply ( go over all supply required structures and collect orders ( list of resource + amount and destination). creep will check if any of orders can be executed and choose best one ( prioritize etc) will come to storages and collect resources, delivering them to intresed party until order is not finished) .

**Comment by mikiones** [comment]
will need some sort of trade - goods moving from bases to move resourced for processing on some point

**Comment by mikiones** [comment]
horrible algoryhm to group labs by 3 but works anyone got better ?

```
if (setCount >=1 ) {
                let l = labs;
                var curent = null;
                var groups = [];
                var limit = setCount * setCount ;// brutal force ?
                while(l.length != 0) {
                    // console.log(1, l.length, groups.length);
                    limit --;
                    if (limit <= 0) break;
                    if (curent == null){
                        curent=l.pop();
                        groups.push([curent]); // add new group beginning
                        // console.log(2, l.length, groups.length)
                        continue;
                    } else {
                        // we have curent to compare against. check all elements left in l for those in range of 1 or less
                       for (var i = l.length -1; i >= 0; i--) {
                            //  console.log(3,'i',i, l.length, groups.length,'r',l[i].pos.getRangeTo(curent));
                           if ( l[i].pos.getRangeTo(curent) <= 2 ) {
                               // found element remove it from array and continue until current group have 3
                               groups[groups.length-1].push(l.splice(i,1));
                               if (groups[groups.length-1].length == 3) {
                                    curent = null; // start looking for more.
                               }
                           }
                       }
                       if (groups[groups.length -1].length <3) {
                           // did not find 3 maching elements ! push back on front the whatever found and start agin.
                           let t = groups.splice(groups.length -1,1);
                           l = t.concat(l); // unmached elements go on front;
                       }

                    }

                }
                
            }
```;
