### ISSUE TITLE
Handle controller.upgradeBlocked 

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#316]
_From @Dasku on November 8, 2016 20:45_

http://support.screeps.com/hc/en-us/articles/207711889-StructureController#upgradeBlocked 

_Copied from original issue: cyberblast/screeps.ocs.internal#7_

**Comment by whardeman** [comment]
Functionally, how should this be handled? Just don't spawn an upgrader? Anything else?

**Comment by cyberblast** [comment]
I think that would be sufficient. It's required quite rare I guess.

**Comment by whardeman** [comment]
Perhaps, if upgradeBlocked ticks > x*creep.ticksToLive, recycle?

**Comment by cyberblast** [comment]
Maybe it's not worth the cpu ;)

**Comment by karlthepagan** [comment]
It's worth it.

Don't get worried about a single addmul when we iterate as much as we do. ;)

**Comment by cyberblast** [comment]
ok. but a single attack adds 1000 ticks blocked immediately. so no comparison required. we should simply do 'if blocked => recycle' then
