### ISSUE TITLE
Register energy spending

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#319]
_From @Dasku on November 8, 2016 20:51_

save energy spent in memory (similar to population)
to generate better statistic
will also enable statistic when at highest controller level (current formula will not work anymore)

_Copied from original issue: cyberblast/screeps.ocs.internal#13_

**Comment by Spedwards** [comment]
@Dasku Would this not be solved with Grafana?

**Comment by chobobobo** [comment]
@Dasku is this issue still relevant?  Memory usage is becoming a concern (wait I think that's your issue too) so is there a specific use case for this?  Energy spent on creeps/structures is a sort in the web client as well.  Re-open with details if needed.
