### ISSUE TITLE
Harvest Power

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#321]
_From @Dasku on November 8, 2016 20:55_

I've seen people doing this, using 2 creeps, one miner and one healer (I assume the miner takes damage)

_Copied from original issue: cyberblast/screeps.ocs.internal#16_

**Comment by cyberblast** [comment]
_From @AVATAR-Phoenix on November 14, 2016 14:28_

The one attacker and one healer is nice, I personally am leaning towards a single unit(ranged heal is not heally enough for me). For me 6M2A3H seems to work out on paper, Has 1.1k health, move 1,1 over plain and 1,1 over road. Attacks 60/tick, heals 30/tick(only 50% of damage is returned). Will output 90k dps in its lifetime, time to spawn 33 ticks and in a perfect world only 23 of these would be needed to destoy a power bank in 5000 ticks(hopefully) :P and on the up side it can be spawned from RCL 4

**Comment by cyberblast** [comment]
_From @AVATAR-Phoenix on November 18, 2016 22:42_

Saw dissi sharing his power knowledge.

Fighter:
![](http://i.imgur.com/i6oDHF2.png)

Healer x2:
![](http://i.imgur.com/yLa9hKB.png)

Hauler
![](http://i.imgur.com/bxkFPhe.png)

Arrangement:
![](http://i.imgur.com/REGyClo.png)

He said it takes about two waves of this to get it down.

**Comment by Dasku** [comment]
done
