### ISSUE TITLE
Create Route Dictionary - utilising PathFinder

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#324]
_From @Dasku on November 8, 2016 21:2_

**Rough form:**

```
[{
  endRooms: ['N0E0','S1W1'] 
  crossingRooms: ['N0W0','S0W0', 'S0W1', 'S1W1'], // without start/destination (only to determine route recalc requirement)
  path: {},
  created: 123456,
  recalulation: 456789 
}]

```

**Usage:**
When a creep needs a route to an other room (not adjacent) it tries to get one from the dictionary. if it doesn't exist it gets created. 
Calculation starts at any Point in the room (creep.pos) to any Point in the other room (target.pos). The path gets trimmed so that there are only up to 2 pos in the end rooms (the gate). 
When a creep gets a stored path it gets combined with a new calculated path from creep.pos to the path gate. The missing path from the end gate to the target can be recalculated once the end of the path is reached. 

**Recalculation:**
When a room completes a new structure (except rampart), all entries in the room dictionary which contain this room in 'crossingRooms' get set to `Math.max(Game.time, entry.created + RECALC_COOLDOWN)`. 
Every entry gets recalculated when this time is reached (wait for cooldown if recalculation happened recently, otherwise recalc immediately).  
TBD whether the costMatrix should get recalculated immediately, once the room structures change, or get a similar cooldown. IF a cooldown will be implemented for the costMatrix, the dictionary entries must not get updated before the costMatrix...

_Copied from original issue: cyberblast/screeps.ocs.internal#19_

**Comment by chobobobo** [comment]
Also, once we have a dictionary of routes, I wonder if it might be possible to "hop on" the route from the nearest point, thus allowing our evade action to find a short route to the nearest free access point to the route rather than recalculating the entire route.

**Comment by karlthepagan** [comment]
dictionaries of routes will be very useful to establish distances within a room with complex geometry.

For example after upgrading the controller in https://screeps.com/a/#!/room/E72S7 the source has the best score with regard to range, but the path distance of the place I'm dropping energy is much better.

With that said. The path dictionary should have a cost number for each point on the path. We can then use PathFinder to join the goal to the path and a second PathFinder to join the actor to the path. This would hopefully result in very little CPU spent on determining distances for nextAction.

**Comment by karlthepagan** [comment]
Another possibility I've discussed recently is that creeps pathfind to the start of the route in the next room and then pick up the trail from there.

**Comment by chobobobo** [comment]
I'm quite partial to this idea, it allows us to focus on what the best route from A->B is within a room, then travelling just needs to decide which rooms it wants to transit on its path, using the best path between exits on its way.

**Comment by chobobobo** [comment]
I think for a first implementation, we can use Traveler.js findAllowedRooms to find the room route to the destination, and we can override the routeCallback to return the ideal path cost to cross from one room to the other.  That ideal path can then serve as our guide for where to build/maintain roads.  This way, paths are still only regenerated after a cooldown when someone tries to use the path, and as long as the cache is valid it just returns the existing cost.

Then we could simply store the list of room names as the travelling route, and load those routes from the cache upon entering each room.

This would require caching the optimal route between any two exits in a room, and the tricky part would be deciding which of multiple exits to take based on your destination..

**Comment by Dasku** [comment]
#869 should succeed this issue.

**Comment by chobobobo** [comment]
closing in favour of #869
