### ISSUE TITLE
Calculate initial Base Setup

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#325]
_From @Dasku on November 8, 2016 21:6_

Dont use claim flag as first spawn position. calculate it. 
- range to sources / controller / mineral
- free space 
- shelter

Determine places for structures not buildable with level 1 (but only first requirements), and overall base design. 

Proactive calculate required roads. Connect common routes. suppress move recording until established.

Don't write code to be implemented. This is task of #326. 

Define RULES, algorithm snippets, formulas. 

What to build where?
What to build when? 
Where exactly (how can the exact pos be calculated?)

**Base design Proposal:**
```
  E E E  
 EEEXEEE 
E\E/T\E/E
EEXSLSXEE
E/E\O/E\E
 EEEXEEE
  E E E
```
E = Extension
T = Tower
S = Spawn
L = Link
O = Storage
X,/,\ = roads

e.g. set road: x+y%4 == 0 || x-y%4==0

_Copied from original issue: cyberblast/screeps.ocs.internal#23_

**Comment by chobobobo** [comment]
I've been manually using a similar base design but am having issues with congestion around the storage with all of the remoteHaulers, I would propose that two of the entrances have double-wide roads rather than single, and that one of those entrances contain the storage.

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1137 resolves this
