### ISSUE TITLE
Extend Observer to look for power

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#330]
_From @Dasku on November 8, 2016 21:20_

Requires #29 

_Copied from original issue: cyberblast/screeps.ocs.internal#30_

**Comment by Dasku** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/828

https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/814

**Comment by Dasku** [comment]
in
