### ISSUE TITLE
Need a waypoint system for attacking/moving creeps

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#334]
_From @AVATAR-Phoenix on December 22, 2016 8:18_

_Copied from original issue: cyberblast/screeps.ocs.internal#127_

**Comment by cyberblast** [comment]
_From @torin555 on December 23, 2016 6:1_

Elaborate?

**Comment by cyberblast** [comment]
_From @AVATAR-Phoenix on December 23, 2016 6:34_

Tried to help mr Dave yesterday and my creeps bashed through two lower level players rooms and then died in a slightly better defended room. So I had to manually move them around with a defense flag which was very time consuming. Maybe have a flag that you nam wp1 wp2 wp3 etc and have certain creeps follow them in order.

**Comment by cyberblast** [comment]
_From @dkluempers on December 23, 2016 7:20_

Agreed, that would definitely be useful - and thanks for the help.

**Comment by forkmantis** [comment]
I am running into issues like this as well.  I was thinking of just making an "avoid room" and when finding routes, filter out rooms that have such a flag. 

This approach should be fairly generic, but may be a bit CPU intensive.  

I can't wrap my head around how you would use more than one collection of waypoints at a time, or how you would map a set of waypoints to a specific task.

**Comment by AVATAR-Phoenix** [comment]
If a flag gets cloaked your units should avoid that rooming I think remote rooms get cloaked when an invader spawns, so maybe just find a way to place cloaked flags

**Comment by Dasku** [comment]
Duplicate issue in #377

**Comment by cyberblast** [comment]
Hmm, the creep could store in memory which flag has been approached already, excluding them when trying to find the next nearest of those flags. Until it reaches a "destination" flag, which will clear that memory and release the waypoint action to select a new one...

**Comment by chobobobo** [comment]
When #665 gets merged in we will have means to avoid rooms which should help in a majority of cases, however in the past I have used flags to navigate safely through SK rooms without angering them.  Perhaps having a group of flag colour combinations where the primary colour represents the entrance to the room (North/East/etc) and the secondary colour represents the exit to the room, creeps could look for those flags and route to them in order.  Alternatively, the entrance/exit and order could be encoded in the name.  Would it satisfy the remainder of our use cases, or is avoiding rooms enough to satisfy this need?

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/751 introduced Memory.rooms[roomName].hostile as well as the previous method of using ROUTE_PRECALCULATION with ROUTE_ROOM_COST, I believe the use case for flag based waypoints has been satisfied.  Future avoidance can be built into the costMatrices of target rooms.
