### ISSUE TITLE
Utilise Labs 

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#336]
_From @Dasku on November 8, 2016 20:37_

Got the minerals now. 

_Copied from original issue: cyberblast/screeps.ocs.internal#3_

**Comment by cyberblast** [comment]
_From @AVATAR-Phoenix on December 1, 2016 9:45_

I'm gonna try and work on this but at first glance how would the scripts know which mineral to produce, would we go with flags or just by what ever is available?

Edit: or manually send the minerals from different rooms and the room then takes the 2 minerals available and mashes them together if it can?


**Comment by cyberblast** [comment]
_From @Dasku on December 1, 2016 10:37_

Hey this is a good question. I think a few things need to be considered:

Which creeps do we plan to boost? All? Specific ones for certain tasks? This is probably the key question, what are our requirements? This should then define the solution. 

Tier 1 components probably needs to be the first stop. 
http://support.screeps.com/hc/en-us/articles/207891075-Minerals

Do we split these minerals up between rooms evenly? Or only send to flagged roomed which would use them for specific tasks? 

I have tried to take new rooms with minerals I don't yet have access to in the hopes of having all minerals available to make all minerals. What happens if someone doesn't have access to a specific mineral they need? Would we buy it off the market?

**Comment by cyberblast** [comment]
Hi, 

I think #6 would be a good start: to have a configuration for each room. 
Maybe in memory...

**Comment by whardeman** [comment]
Here's my idea. Anyone who wants to jump on this (I may have some time soon, but who knows...) please feel free to run with it.

Assumptions:
- Minerals will need to be moved from one room to another. This can be done via
  - Terminal transfers (same player, player to player, market purchase)
  - One-way creep shipments
- Labs need to be placed by player
- Labs need to be "designated" (probably with flags) by the player.

So, the general flow of requirements is:
1. [UI] Place labs as required
2. [UI] Designate a target lab for desired compound (more on this later) 
3. Determine required minerals to make desired compound 
4. Designate feeder labs with dependency compound flags
5. Check that feeder lab requirements are satisfiable
  - If feeder lab requirements are not satisfiable, repeat from step 3 for dependency compound
6. Begin filling lowest tier mineral and energy requirements 
7. Generate dependency compounds up the chain until desired compound complete

To move foward, we could start at any point in the supply chain:
- Acquiring minerals
- Lab setup and designation (includes compound dependency detection)
- Mineral & energy distribution to labs
- Lab processing

**Comment by whardeman** [comment]
Any ideas on other UI triggers, critical steps missed, etc, please give your feedback.

**Comment by Dasku** [comment]
I'd like to use CYAN :)

I've been thinking about this a lot too actually. My rough ideas at the moment:

Task governs a couple things, production and distribution. 
Spawns a lab technician(hauler) moves minerals between terminal storage and labs(when required). Do you need flags? as long as you place them in 3's it should be ok? We could specify how they need to be placed. 

I suppose there is 2 ways to go:
1) Distribute all base minerals to all rooms, create all minerals in every room.
2) Distribute base/lower minerals to set production rooms, which then distribute out the usable minerals to all rooms 

Personally I figure option 1 is the simplest way to go to start off (maybe improve later). Also this means you don't need to designate all your rooms or use flags. Technically the minerals will take the same amount of time to create in every room anyway. 

Maybe then in memory each room updates (every 1000 ticks or something) its total of each mineral. Your storage should hold 20k of each  base mineral and then make the rest.. From what I've seen in other players rooms they make/store 2000-6000 of each mineral in their storage. 

Base minerals should be passed out to each room and once every terminal you have has 20k of a rooms mineral and that room has 50k in storage, sell the excess.

We start with the basic compounds and then just add the more advanced minerals later?

I think the distribution or management of all the minerals will be the hard part. If each room is supplied base and works up the chain that could be the "base". 
Then we implement another way of moving specific minerals to specific rooms for specific tasks at specific times later with strategies or something?

**Comment by webremote** [comment]
If we start with flags to get minerals from storage to labs, I would be so happy!

I've got some minerals locked in storage and can't get them anywhere near a lab. If flags can be used on labs, the (current) haulers move them from storage to lab. If the name of the flag represents the desired resource, you'll need less colors.. (i.e. same for creating minerals, if two labs have resource_x and the other lab has a flag with resource_x, the room checks if resource_1 + resource_2 = desired flag)

global distribution should be a different task/system, there's one open i think

**Comment by cyberblast** [comment]
Personally I'd prefer not using flags. There are so many compound types. Whats wrong with a room configuration in memory. (sorry there was a wrong issue pointer above) Room configuration could look like this; https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/338. 

To start producing OH one could do `Game.rooms['roomName'].memory.config.production.push('OH')`. 
We could also simplify such commands like: `commands.produce('roomName', OH)`

**Comment by karlthepagan** [comment]
I've started shortening command line methods to something like `Task.labs.produce(roomName,...args)`

**Comment by Dasku** [comment]
I found some public lab code which could give some ideas about how to use the lab without need for flags:

       getSourceLabs: (room) => {
            "use strict";

            var labs = Cache.labsInRoom(room),
                sourceLabs = [];

            _.forEach(labs, (lab) => {
                if (Utilities.objectsClosestToObj(labs, lab)[labs.length - 1].pos.getRangeTo(lab) <= 2) {
                    sourceLabs.push(lab.id);
                    if (sourceLabs.length >= 2) {
                        return false;
                    }
                }
            });

            return sourceLabs;
        },

        getLabToBoostWith: (room, count) => {
            "use strict";

            var labQueue = room.memory.labQueue,
                sourceLabs = (labQueue && labQueue.sourceLabs) ? labQueue.sourceLabs : [],
                labs = [],
                labToUse = null,
                lab, labUsed;

            if (!count) {
                count = 1;
            }

            if (sourceLabs.length === 0) {
                sourceLabs = Utilities.getSourceLabs(room);
            }

            if (!room.memory.labsInUse) {
                room.memory.labsInUse = [];
            }

            for (let index = 0; index < count; index++) {
                // Try to use labs other than source labs.
                labToUse = {};
                lab = _.filter(Cache.labsInRoom(room), (l) => sourceLabs.indexOf(l.id) === -1 && _.map(room.memory.labsInUse, (liu) => liu.id).indexOf(l.id) === -1 && _.map(labs, (liu) => liu.id).indexOf(l.id) === -1);

                if (lab.length > 0) {
                    labToUse = {
                        id: lab[0].id,
                        pause: false
                    };
                }

                // If only source labs are left, we will need to pause the reaction and use one of them.
                if (!labToUse || !labToUse.id) {
                    labToUse = {
                        id: _.filter(sourceLabs, (l) => _.map(room.memory.labsInUse, (liu) => liu.id).indexOf(l) === -1 && _.map(labs, (liu) => liu.id).indexOf(l) === -1)[0],
                        pause: true
                    }
                    
                    if (!labToUse.id) {
                        return false;
                    }
                    labUsed = Game.getObjectById(labToUse.id);
                    if (labUsed.mineralAmount > 0) {
                        labToUse.status = "emptying";
                        labToUse.oldResource = labUsed.mineralType;
                        labToUse.oldAmount = labUsed.mineralAmount;
                    }
                }

                // If no labs can be used, then we can't boost.
                if (!labToUse.id) {
                    return false;
                }

                labs.push(labToUse);
            }

            return labs;
        },

        roomLabsArePaused: (room) => {
            "use strict";

            return room.memory.labsInUse && _.filter(room.memory.labsInUse, (l) => l.pause).length > 0;
        }
    };

**Comment by logxen** [comment]
I have come up with 3 different concepts for lab layouts that I would like to share. It's very difficult to move a lab so I'm trying to work with concepts that scale all the way to the full 10 labs a level 8 room can have. Currently I'm thinking I want to have a type II "Block" for my first room and then a type III "Pyramid" for my second room. This strikes me as the simplest path to efficiently producing catalyzed ghodium compounds. :)

# I: Basic Three
Just use 3 sets of 3 labs each. Simple. In fact, all 3 plans are effectively on this path at RCL6. The 10th lab could be added to one of the sets to double its output rate.
`.....`
`..3..`
`.1.2.`
`.....`

Pros:

- simple to code and understand

Cons:
- extra work for transport creeps
- extra work to to make higher grade compounds
- lots of flags to control

# II: Versatile Block
This concept puts all the labs in a cluster. 7 of them are just kept stock with each of the 7 minerals. The remaining 3 labs are used for production.
`.....`
`..0..`
`.789.`
`.456.`
`.123.`
`.....`
Labs 1, 2, 3, and 5 would be stocked with the core minerals U, K, L, and Z.
4 and 5 would be stocked with H and O.
8 would be stocked with X.
7 and 9 can pull from any lab to create first tier compounds.
10 can pull from 7 and 9 to create second tier compounds.
To create a third tier compound (catalyzed) would require finishing a batch of acid/base, then reusing 7 or 9 to create the catalyzed compound from 8 and 0.

Pros:
- Can create any compound "on demand"
- Relatively simple to code
- Can create G efficiently (1 G per tick)
- Only requires 3 control flags for output labs
- Compact layout

Cons:
- Takes 2 phases to make catalyzed compounds
- May have transport issues that would require extra containers for H and O nearby?

# III: Pyramid
This idea is to stack Basic Three reactors onto each other, effectively reusing the output reactors as sources for the next tier reaction.
`.........`
`.......0.`
`.....8.9.`
`...6.7...`
`.12345...`
`.........`
2 and 4 get H, 3 and 5 get O, 9 gets X.
A flag on 1 selects one of the 4 main minerals U, K, L, or Z with its color. That mineral is then stocked into lab 1.
A second flag or the second color of the first flag selects whether lab 2 or 3 will be used to make acid or base.
1 and 2/3 combine into 6, 4 and 5 combine into 7 giving us our first tier compounds.
6 and 7 combine in lab 8 for second tier.
8 combines with the X in 9 to give fully catalyzed compounds in lab 0.

Pros:
- Can create catalyzed compounds efficiently (1 per tick)
- Very easy to use, only 1-2 flags to control the entire reactor
- Should be pretty easy to code

Cons:
- Specialized in making catalyzed compounds (or it would become complicated to code and control)

**Comment by Dasku** [comment]
You all seen this? I don't really understand it.

https://www.youtube.com/watch?v=hBm8QumM80A

**Comment by Spedwards** [comment]
@logxen @karlthepagan This resolved?

**Comment by Dasku** [comment]
taken care of by resource management - new issues for further improvement.
