### ISSUE TITLE
Utilise Boosting

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#337]
_From @Dasku on November 8, 2016 21:6_

Relies on #3 

_Copied from original issue: cyberblast/screeps.ocs.internal#22_

**Comment by whardeman** [comment]
Does this really belong in public?

**Comment by karlthepagan** [comment]
The framework for assigning boosts IMO yes.

Strategies for who gets military boats no IMO.

**Comment by cyberblast** [comment]
hmm. I agree with whardeman. This shouldn't be discussed public.
