### ISSUE TITLE
terminal to also support RCL 8 rooms in energy crisis

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#344]
_From @cyberblast on December 20, 2016 21:42_

Have a collapsing room actually. unsure why. But the rich rooms should send money ;)

_Copied from original issue: cyberblast/screeps.ocs.internal#117_

**Comment by chobobobo** [comment]
Terminals can send energy to RCL8 rooms, the check for RCL has been commented out in room.js, but I'm not sure when that was implemented.
