### ISSUE TITLE
Add command for signController

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#346]
_From @dkluempers on December 21, 2016 16:30_

It might be nice to add a command in command.js to clear or set sign information for controller.  I consider this very low priority.

_Copied from original issue: cyberblast/screeps.ocs.internal#122_

**Comment by cyberblast** [comment]
_From @erik-smit on December 21, 2016 17:38_

Very low priority, but also very easy to solve.
I'm looking forward to seeing your pull request. ;)

**Comment by cyberblast** [comment]
_From @dkluempers on December 22, 2016 5:45_

I have never used GIT so this should be interesting.  Perhaps this weekend.

**Comment by cyberblast** [comment]
_From @TafThorne on December 22, 2016 6:46_

Using git and using git with GitHub are two slightly different work flows.  As long as you stick with just using the commands; clone, log, status, pull, add, commit and push things should be straightforward.  Have you used any other version control systems before?  I could help make comparisons with them if you like.

**Comment by cyberblast** [comment]
_From @TafThorne on December 22, 2016 6:51_

I was also thinking about using the message feature today.  My thoughts were that Claimers and Upgraders could automatically add

- `<PlayerName> of OCS` to controlled rooms to make alliance affiliation clear
- `Claimed by <PlayerName> of OCS` to claimed rooms to illustrate mining claims
- Maybe something like `Soon To Be Part Of OCS` to rooms that are getting reserved before a spawn will be built
- There are all only set if the message is blank.  That should preserve any player set ones.

**Comment by cyberblast** [comment]
_From @dkluempers on December 22, 2016 7:39_

I like that idea.

**Comment by cyberblast** [comment]
_From @dkluempers on December 24, 2016 17:33_

I am testing with my code now.  I added a parameter called SIGN_CONTROLLER_MESSAGE to parameters.js with the message.  I updated the creep.action.reserving to add a couple of lines of code action.work method.  That seems to work.  But I think it needs to be added creep.action.charging as well.  I will try that also.

**Comment by cyberblast** [comment]
_From @webremote on December 29, 2016 14:9_

referencing https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/309

**Comment by dkluempers** [comment]
Thanks for the update.  I will close this out.
