### ISSUE TITLE
Workers don't return to homeRoom

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#348]
_From @Dasku on November 13, 2016 19:29_

I was building a path near the edge of a room and the workers would sometimes leave that room into a passage way room (the ones with no sources between blocks). This room has construction sites in it for roads, so the workers began working on those instead. After they became idle instead of returning home.

We could add a home check to action.idle but this could have repercussions on fighting units if all flags are deleted they would return home.

_Copied from original issue: cyberblast/screeps.ocs.internal#48_

**Comment by Dasku** [comment]
Just started to get this same issue again where my new base is, just have a line of workers in a corridor room with no sources that accidentally move out of the home room.

**Comment by Dasku** [comment]
Working now
