### ISSUE TITLE
Allow Fighter To Fight Off Invaders In Safe Mode

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#350]
_From @TafThorne on December 21, 2016 10:51_

Possibly limited to the start of the game.  When safe mode is activated it seems that melee units do not attack non-player owned creeps entering a room.  This behaviour is the same whether there is a defence flag, invasion flag or no flag set.  

Conversation with @mmmd suggested a work around for the beginning of the game.  
------

taft [9:42 AM]  
What is going on with these transparent creeps? https://screeps.com/a/#!/room/E78S34

[9:43]  
Is it safe mode disabling them somehow?  If it is then how come my defence creep isn't trying to kill them off?

mmmd [9:50 AM]  
yes it is the safemode ... don't know why your creep is ignoring them (edited)

[9:50]  
they are transparent because you can also pass over them i think (edited)

[9:52]  
aah this is so mean

[9:52]  
Next level: 13.8M / 13.8M

crowsbane [9:56 AM]  
SafeMode is conisdered in invasion status

mmmd [9:58 AM]  
yeah still even if you are in safemode the fighty creep should attack the enemy creeps

[9:58]  
no point in doing nothing

taft [9:59 AM]  
That was my thoughts.

[9:59]  
At least if i have a creep he could be blowing them up and harvesting the scrap.

[10:03]  
Gonna take a while 8791 / 45.0K
That is since around 12:15 last night.  Not much progress for 10 hours work.

mmmd [10:05 AM]  
added and commented on a JavaScript/JSON snippet 
```javascript
    let fighters = _.filter(Game.creeps, c => c.getActiveBodyparts(ATTACK) > 0);
    for(let fighter of fighters){
        let target = fighter.pos.findClosestByRange(FIND_HOSTILE_CREEPS);
        if(target){
            fighter.moveTo(target);
            fighter.attack(target);
        }
    }
```
1 Comment Collapse
add this to the end of your main loop for now

mmmd [10:05 AM]  
and we should write an issue for it in the repo ... i don't want to wrangle with the fighter behaviour right now

_Copied from original issue: cyberblast/screeps.ocs.internal#120_

**Comment by cyberblast** [comment]
hmm, I guess we could allow defense during safemode by updating Creep.action.defending.isValidAction. 
old: 
```
action.isValidAction = function(creep){ return creep.room.situation.invasion; };
```
new: 
```
action.isValidAction = function(creep){ return creep.room.hostiles.length > 0; };
```
Anybody can validate that?

**Comment by whardeman** [comment]
Is this issue resolved by the above changes? Can this be closed?
