### ISSUE TITLE
Defender behavior needs improvement

### ISSUE THREAD

**Issue by Krazyfuq** [ScreepsOCS/screeps.behaviour-action-pattern#375]
I had a small room attacked and when I dropped a defender flag all that spawned were rangers?
4 large rangers against 4 small melee'rs and the rangers lost.

The rangers focused on one target and will avoid that target only, so the other melee's gang up and take the rangers down one at a time, the rangers wont move from the other attackers only the one in focus.

Choose closest target - attack - move?

**Comment by cyberblast** [comment]
Hi Krazyfuq, 

sorry about that. 
You are welcome to propose a better approach. 

What would it be that you have expected? 
You may also want to clone this repo, develop a change and create a pull request to implement such enhancements.

**Comment by Krazyfuq** [comment]
Hi Cyberblast,

No need to be sorry, was more a FYI and hopefully some one smarter at this would be able to improve. I have no experience with java and would not have been able to use your code if not for the guild that is posted. I do not know how to do a pull but I will work on that.

I think the rangers would have won the skirmish easily if 1st priority is avoid closure of any attackers and ability to switch target. Like i said it is beyond me how and if this is possible. Was also curious why only rangers were spawned?

Sorry I cant help more with the project and if this is the wrong forum for this type of comment please let me know.

Keep up the great work on the code guys.

**Comment by misterwise** [comment]
To add to this discussion, I noticed that after the battle has finished, defenders who can heal return to be recycled, it would also be good if they healed damaged creeps in the room before they leave.

**Comment by SEATURTLEKING** [comment]
i agree with @misterwise. maybe there can be defender logic

**Comment by SEATURTLEKING** [comment]
defenders all focus on different targets and if there is only one attacker attacking then they all gang up on them, and so on, you guess can add your idea's

**Comment by SEATURTLEKING** [comment]
made an idea about defender logic #1025

**Comment by chobobobo** [comment]
closed in favour of https://github.com/cyberblast/screeps.ocs.internal/issues/268
