### ISSUE TITLE
Pioneers returning home after reaching designated room.

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#376]
3 pioneers have now walked 4 rooms to the location, gone inside, turned around and walked home.

Spawn: E73N59
New Room: E73N55

I had a white/white and a white/red, claimer came, construction site appeared with white/green flag as normal. Pioneer which was already there from the white/red flag left (I assumed because I'd messed the flags up or something), waited and next one left too, deleted the white/red flag so only a white/green and 3rd one still left.  

Need sleep, will leave on with white/green over night and hope it works.

**Comment by Dasku** [comment]
A stream of them have just returned back now. Deleted all flags and construction site and added a white/white again.

**Comment by Dasku** [comment]
Ahhh!! I think I know why, workers return home now !! 

I think we need to change their home room once they arrive?

**Comment by cyberblast** [comment]
oh, yes ^^. or we let worker only return home if the are real "worker".

**Comment by dkluempers** [comment]
Tested today and still having issues.  Trying a couple of things like Dasku to see if that works.

**Comment by Dasku** [comment]
The fix that cyber implemented has fixed this issue for me, try updating your code.

**Comment by dkluempers** [comment]
Ok, I unclaimed the room then placed a claim flag white/white.  No claimer seemed to spawn so I manually spawned it.  Claimer turned claim flag to white/greet.  Pioneer was spawned.  I manually changed it homeRoom and it stayed and started working in the new room.  3 more pioneers were spawned.  I did not change their homeRoom and they seem to be working ok.  I have noticed that I tried to reserve room W1S79 below my room, but no claimer is being spawned.  I will continue testing.

**Comment by dkluempers** [comment]
Checked again this morning no claimer for the room I reserved with White/Grey.

**Comment by Dasku** [comment]
Sorry why White/Grey? That would only send a claimer to reserve (no privateers and no claiming the room).

If you have the latest code a white/white should work, if you own the room already (from yesterday), a white/green where you want the spawn and a white/red for extra pioneers should do the trick?

**Comment by dkluempers** [comment]
I am thinking this was working correctly now since I was actually working now.  I will try claiming another room tonight to see if it works.

**Comment by TafThorne** [comment]
Put down a white/white flag where you want a spawn to eventually go.  I did this yesterday and I got a claimer sent out then once the room was claimed some pioneers went to build the spawn.  I did not have to set any flags after the first white/white one.  

You can set extra flags to send more pioneers to help build the first few structures.
You can set defence flags to have some military units sit there.  

Goodluck!

**Comment by dkluempers** [comment]
I claimed another room last night and everything seemed to work fine.  Pioneers were spawned and went to the correct room.

I have seen one error having to do with defend flags but I will open a separate issue for that.  Thanks!

**Comment by Dasku** [comment]
Working now
