### ISSUE TITLE
Guarding flags and new spawning

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#377]
Just noticed with the new creep to flag spawning, when you get a group of rangers say, you use 3-4 flags, when they spawn you set a new flag a couple rooms away and delete the first ones, on the way their another spawns for the new flag, then another when you move the flag again, then another for the red flag in the room your attacking and so on and so on. 

Should their be a neutral flag which creeps will follow without spawning new creeps? Like yellow yellow is now. Then have yellow/yellow as a trigger to spawn a new creep.

**Comment by whardeman** [comment]
I noticed just recently that creeps are spawning with names that match the name of the defend flag I place. That is a recent change, right?

Also, I toyed around with this a bit, and it seems like at the time, if I had a group of military creeps, I could direct them using a couple tricks. 
1. Deleting all flags except one, and repositioning that flag (either by point-and-click or flag.setPosition method). This prevents unnecessary spawns since the flag is already tracked.
2. New flags using yellow as primary color and any other color as secondary to direct the military creeps without spawning new ones. Not sure if that was intended. I didn't think much of it at the time.

**Comment by Dasku** [comment]
I think this has only been introduced recently, as the maxCount was based on number of flags, so if you spawned 10 creeps, when you deleted the other flags more creeps wouldn't spawn as there was more creeps than there was flags already. 

I like your option 2, just a "gather here" type neutral flag which doesn't spawn anything.

**Comment by Dasku** [comment]
Thinking about this more, would a neutral "gather here" flag have more uses? Like guiding creeps through the middle 9 squares without them attacking the sourcekeepers? (I believe they only attack if you go close, attack them or try to mine)

**Comment by whardeman** [comment]
I think that's exactly how it has worked for me when I've used it, actually. While taking down a reasonably well-defended low level room, I positioned my creeps just outside at the exact spot where I wanted to enter and begin attacking. I used a Yellow/Green flag or some such after all of them had spawned or started spawning and once they had grouped, I dropped the RED flag to invade the room.

**Comment by Dasku** [comment]
Just realised this is a duplicate issue already in #334

**Comment by torin555** [comment]
orange orange has never spawned anything for me, that's just a target flag in an invasion.

**Comment by Dasku** [comment]
Hmm, its hard for me to tell right now what is spawning what, but when I checked a creep had spawned named Flag9 which was an orange/orange. 

However you could be right, I was changing flags so much to test things it could have just took a while to spawn from the queue which confused me.

**Comment by cyberblast** [comment]
Regarding the original issue (create a new flag, only to let creep follow, without spawning a new one): 
You can try to create a new yellow/yellow flag with the same name as the existing one. This way the existing one gets removed. 
But the new flag will keep the flag's memory. So it's like moving a flag, but even across rooms ;)

**Comment by cyberblast** [comment]
Is is still an issue?

**Comment by cyberblast** [comment]
Assumed to be not. Please reopen if it is...
