### ISSUE TITLE
(old issue) Room dies out at level 3-6

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#381]
Thought we had fixed this a while ago, but I have 3 rooms, one level 5, one 3 and one just started. 

Woke up this morning with no pioneers in the newest room, when I checked my level 5 room has died out.

Trying to get a pioneer there from my level 3 room, however should we not have a mechanism which spawns a 200 worker when a colony is dead? Just to reboot things

**Comment by Dasku** [comment]
![image](https://cloud.githubusercontent.com/assets/22677773/21592570/70e360d6-d106-11e6-92c8-998d9584b091.png)

**Comment by Dasku** [comment]
Just checked my reply and the same happened, everything just froze, then it spawned 2 miners and 1 privateer, they died and the room stopped.

**Comment by whardeman** [comment]
Sounds like we need a 'roomDied' flag or something for sure that resets spawn priority.

**Comment by Dasku** [comment]
Sounds good, Or make hauler higher priority than a miner, now they have 1 work it could act as a miner/worker if nothing to uncharge or withdraw? Miners are great unless there isnt enough energy to spawn a hauler as well.

**Comment by webremote** [comment]
workers would be preferred, as they would make sure the spawn gets enough energy from sources

**Comment by whardeman** [comment]
Yeah. Could detect if there is enough available energy in containers/storage first, if none, then do workers, otherwise build haulers.

**Comment by Dasku** [comment]
forkmantis [4:47 PM]  
right now he's just dumping onto the ground

[4:47]  
the problem is that they are prioritizing building over refilling the extensions

[4:48]  
and by "they", I mean any of my creeps

asku [4:48 PM]  
oh yeah :confused:

[4:48]  
whats the priority order?

forkmantis [4:48 PM]  
I guess building at this point

[4:48]  
must have changed recently

[4:48]  
because it used to fill extensions first

asku [4:48 PM]  
priority = [
                   Creep.action.repairing,
                   Creep.action.building,
                   Creep.action.fueling,
                   Creep.action.fortifying,
                   Creep.action.feeding,
                   Creep.action.upgrading,
                   Creep.action.charging,
                   Creep.action.storing,
                   Creep.action.idle];

[4:49]  
switch fueling and building and it should be ok ?

forkmantis [4:49 PM]  
is that from worker behavior?

asku [4:49 PM]  
yep

[4:49]  
I think this is the priority because it is assuming there is a hauler

[4:49]  
which should prio the extentions first

[4:50]  
again this should be a low level issue

xephael [4:50 PM]  
that's a bad assumption

asku [4:50 PM]  
but something i mention in the issue post about my room dieing

[4:50]  
if hauler had prio over miner i think this would fix it

[4:51]  
or workers doing extentions first would also fix but slow down the building when things are running correctly

xephael [4:51 PM]  
we switched it to workers doing extensions first ages ago because tons of rooms died, but apperantly someone switched it back

georgeberkeley [4:51 PM]  
It's worse. If there is a hauler, but energy containers are being depleted for building/repairing, the hauler will idle.

asku [4:52 PM]  
workers should withdraw before uncharging

[4:52]  
i was looking at that last night also

[4:52]  
as my workers were walking for miles to get energy when building next to a container being filled by a miner

georgeberkeley [4:53 PM]  
I'm currently building Storage and the pioneers/workers are focusing on that and preventing spawn/extension feeding.

[4:54]  
So I've flipped those two until things get back on track

[4:54]  
Now spawns/extensions are full and the Storage is getting finished.

asku [4:55 PM]  
Yeah, I think it was a similar that was causing a level 6 room wipe when you build a terminal as it requires 100k energy and forces work on that for a long period of time

xephael [4:55 PM]  
yeah

georgeberkeley [4:55 PM]  
yeah exactly

new messages
xephael [4:55 PM]  
but idk why that got switched back, because we changed that priority months ago

**Comment by Dasku** [comment]
All my rooms lived last night, if no one else had issues I'll close this.

**Comment by Krazyfuq** [comment]
When my main room hit 6 all was good until I built the mineral extractor. I came back a couple hours later and the room was colapsing. No haulers or workers and extensions were just about empty, I spawned a worker and his main focus was to pickup the minerals he would go pickup energy as well but it seemed he was more focused on minerals, I called a pioneer and he acted the same way, I had to remove the mineral extractor to get the room up and running again. I will wait for the labs and then try the extractor again.

**Comment by Dasku** [comment]
Hi Krazyfuq,

So the fix I have submitted has not been committed yet (might be worth cyber taking a look at the issue and ensuring the fix I've suggested will actually fix it longer term).

If you want to change this yourself now, open up  creep.behaviour.worker.js

On the line 43 onwards priorities, change it so feeding is higher than building as priority.

               priority = [
                    Creep.action.repairing,
                    Creep.action.feeding,
                    Creep.action.building,
                    Creep.action.fueling,
                    Creep.action.fortifying,
                    Creep.action.upgrading,
                    Creep.action.charging,
                    Creep.action.storing,
                    Creep.action.idle];

**Comment by Krazyfuq** [comment]
Thanks Dasku, should fix the issue i had

**Comment by Dasku** [comment]
Seems to be working for now
