### ISSUE TITLE
Creep birth and death console notification's work only for some creeps

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#385]
It seems like for me that the creep notifications

> [9:23:39 AM] E75N57 > Good morning worker-1200-1!

Only seem to appear for maybe half of the creeps spawned now. This makes it difficult for me to know what spawns are creating what creeps and if my forced spawns (such as military creeps) is working, often leading me to over produce.

Could we change this notification so it is generated by the task creating the creep so it appears for every creep produced instead of just the creeps which has the code still working properly?

**Comment by cyberblast** [comment]
Hmm, that shouldn't be the case. Every creep, no matter if spawned using the "setup" approach or "queue" approach should get a census announcement (except if turned of completely). 
Only when you call spawn.createCreep directly (which shouldn't be the case), there will not be an announcement.

**Comment by Krazyfuq** [comment]
I've not noticed any missing announcements. I do have a question regarding the spawn numbering, does the numbering represent anything? Where can i find this info if so?

**Comment by Dasku** [comment]
The first number is the energy cost of the creep, and the second number is just a unique ID for that creep

Name-Cost-No.

**Comment by Dasku** [comment]
I'll keep an eye on it, I could have been wrong here
