### ISSUE TITLE
Pathing issue? Claimers confused. 

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#388]
![image](https://cloud.githubusercontent.com/assets/22677773/21617971/9ec88438-d1e0-11e6-9c58-02be8f849351.png)

Here you can see 2 claimers going from the door on the right to the door on the bottom, back and forth.

Prior to this I've had several claimers going in and out of the bottom door until they die.

Can they not find the controller because its a weird path? If I build a road to the controller would that save or create a new path so claimers could find it?

**Comment by cyberblast** [comment]
do you have ROUTE_PRECALCULATION set to true?

**Comment by Krazyfuq** [comment]
I have one room with the same problem. I have had the room for days now and now the claimer seems confused the claimer goes in and retreats and heads to the second room I have claimed. The second room has a claimer on it so this claimer will turn around and go back to the original one and repeat this action.

I was thinking of removing the flag and the room from memory and drop the flag again, would this help?

**Comment by Krazyfuq** [comment]
was set to false will try true

**Comment by cyberblast** [comment]
> I was thinking of removing the flag and the room from memory and drop the flag again, would this help? 

Maybe, I have no idea currently... 

> was set to false will try true 

You may try, but I'd strongly advice to keep this one set to false, as it is still experimental. And last experiments didn't work quite well...

**Comment by Krazyfuq** [comment]
hmm, that did not work so as you suggested I put back to false.

removing the flag and the room from memory did not work either, tho this time he came all the way down to the controller took a look and then retreated, this is weird because I have had the room for days.

**Comment by Dasku** [comment]
Mine is also ROUTE_PRECALCULATION: false.

**Comment by Dasku** [comment]
Ok I've been watching a couple going in and out at the side for a while. I dropped a white/grey flag and one walked half way to the controller and then turned back, the other one (which when i dropped the flag went to another exit) then went to the controller, almost got there and then turned around. Its like their job is changing constantly, switching tasks and never getting there. Maybe before I dropped the white/grey flag this was happening everytime it switched room

**Comment by Dasku** [comment]
It is, the 2nd one leaves the room, comes back in and they switch tasks.

**Comment by Dasku** [comment]
Killed one and it reserved it, maybe this will sort it now.

**Comment by Dasku** [comment]
I think 2 rooms may be sending claimers to reserve the same room which might be causing the issue?

**Comment by whardeman** [comment]
@Dasku I have seen this happen when a claimer targets a room already being reserved. The reserving creep stops reserving immediately and leaves the room when the new claimer arrives.

**Comment by cyberblast** [comment]
Hmm. strange. 
I added some stabilizing changes in fix/claimerBehaviour. You may check if this is of any help, but I have no idea yet.

**Comment by Krazyfuq** [comment]
So far looks good, claimer is back on the room

**Comment by cyberblast** [comment]
oh, great :)

**Comment by Dasku** [comment]
Thanks cyber will test this today also.

**Comment by Krazyfuq** [comment]
Checking in this morning and the room I had trouble with I now own and a new room I set for harvesting is having the same issue. I have 2 with the red/green flag one is fine but the new room the claimer leaves.

**Comment by Krazyfuq** [comment]
Like Dasku I put down a white/grey flag and the room got claimed, left it like that for a few hours and when I got back I removed the white/grey and again the new spawned claimer enters and leaves the room.
