### ISSUE TITLE
spawnQueueHigh with zero part creep prevents Room from ever spawning

### ISSUE THREAD

**Issue by whardeman** [ScreepsOCS/screeps.behaviour-action-pattern#396]
One of my rooms died today. All the other rooms were fine, but in this one, no creeps would ever spawn. After hours of debugging, somehow this had gotten into the spawnQueueHigh array:

```
    {  
        "setup":"upgrader",
        "name":"upgrader-0-1",
        "parts":[  

        ],
        "cost":0,
        "mother":"Spawn3",
        "home":"W76S47",
        "breeding":1
    }
```

The immediate fix was to run `Game.rooms[<roomname>].spawnQueueHigh.pop();`

Not sure how that happened, but I think we need a check that automatically removes zero body part creeps from queues, or rooms will die very quickly.

Thoughts?

**Comment by TafThorne** [comment]
I think there are (or were) issues with the room collapse and recovery code.  When no other creeps exist in the room it need to start generating workers as a safe recovery path.  

In the past, when attacked I have seen haulers fail to spawn as there were no miners.  This meant no energy harvesting or movement.  It does not take long for the whole economy of the room to collapse in these cases.  

Using a worker might be slightly inefficient but it is better than collapse.  One or two very simple workers are enough to refill extensions and start the pathway to recovery which can be very fast if energy is available in storage. Even a more complicated check that added a hauler to the start of the queue if there was a few thousand energy in the storage would help.

**Comment by cyberblast** [comment]
Ouch. 
Hmm, there should be a check in spawn.createCreepByQueue to simply remove that entry. 
But we should also have a look that this doesn't happen at all (queueing zero part creeps).

**Comment by cyberblast** [comment]
hmm, there is an approach to change worker spawning in #391. 
We should maybe add to increase worker spawning priority. 
This way the worker will be the first creep spawned after a wipe.

**Comment by whardeman** [comment]
> In the past, when attacked I have seen haulers fail to spawn as there were no miners. 

Yes, this is still the case. When my room died out I had LOADS of energy available, but running `createCreepBySetup(Creep.setup.hauler)` just returned `null` so I had to force spawn a miner first.

**Comment by torin555** [comment]
you can use the spawn queue command to spawn creeps and bypass the normal spawn requirements

**Comment by whardeman** [comment]
Yes, and I've done that, but it's very inconvenient. 😏

**Comment by torin555** [comment]
more convenient than manually spawning a miner first lol

**Comment by TafThorne** [comment]
Just spawn a worker and all will be well again in a few minutes.  

I thought I had seen a recent code change about making sure there is at least one worker in a room after a population collapse.  I think room does have to have zero creeps in it but that kind of happens with a population collapse and the recovery happening at all in the six hours you are sleeping is much better than waking up to an empty room.

**Comment by Dasku** [comment]
#400 should fix this? Could someone please confirm?

**Comment by cyberblast** [comment]
yes, @whardeman confirmed at #400
