### ISSUE TITLE
Pioneers Not Going To Help New Room (Change Pioneers to task based)

### ISSUE THREAD

**Issue by TafThorne** [ScreepsOCS/screeps.behaviour-action-pattern#397]
I have a new room to the north of some current rooms.  I have set two White/Red flags in it to request that extra pioneers get sent to help out with the low level building.  So far no pioneers seem to have gone there since the spawn was constructed and that was ~ 24 hours ago.  

![image](https://cloud.githubusercontent.com/assets/586550/21635809/b583e128-d257-11e6-88a8-b68be7dbb472.png)
This is the map area between my established rooms to the south and the room not getting help to the north.

**Comment by TafThorne** [comment]
I might have found at least part of the problem.  (Why does that always happen just after you file a bug despite checking lots before hand?!)

In the room at the bottom right of the image there was also a White/Red flag.  This room is now level 6, as is the more central room.  On closer inspection there were at least two pioneers sat in that lower right hand room.  

I have now removed the pioneer flag in the lower left room.  I can see the creeps have started to move, probably up to the top room.  This one might be entirely down to human error.  

We might want to automatically remove these flags when a room reaches a level where it could generate its own pioneers.  Then again thinking about my comment in #396 about needing a worker for recovery... another room could always send in a pioneer to help the recover.  There are probably other times when sending helper worker to a room might be a good thing but I cannot think of many past when a room has enough spawns to make its own.

**Comment by cyberblast** [comment]
Yes there is a general problem with paling pioneer flags in multiple rooms (far away rooms will never get a pioneer). 
This should become better after converting that to the task based approach.

**Comment by Dasku** [comment]
Relates to #343

**Comment by Dasku** [comment]
Now in, further improvements via new issues.
