### ISSUE TITLE
Hauler picking priority

### ISSUE THREAD

**Issue by Krazyfuq** [ScreepsOCS/screeps.behaviour-action-pattern#412]
I have moved the picking priority for haulers to last priority.

The reason for this came from a room collapse on my local server that was running an older dev. I haven't paid much attention to it for a few days. When I last checked all rooms seemed stable at RCL6, room 3 I finished everything except a few extensions to be built when I logged out. I believe the collapse started in this room, none of the remaining extensions were complete and it was the most decayed room. This room was tough to get up due to location of the sources and controller and the fact everything was in swamp.

To recover I decided to update to the lastest dev and manually spawn a worker in all three rooms.

Rooms 1 and 2 not so bad recovering with the 1 carry slot worker (hauler with picking as last priority would have been better), but room 3 was a completely different story I found it kind of funny actually. The room has 3 links all were full and long walk through swamp to get to both source of energy and both short cut roads to the energy mostly gone from decay.

So off goes this little worker through the swamp to mine, I'm thinking shit this is going to take forever to get the extensions filled I should have spawned a hauler with the links full the hauler could get the spawning done quicker (I did not realize hauler had picking first as well). So now I have no choice but wait it out, I dropped a flag for pioneer help but the other rooms were not fully functional just yet so that would be a while.

So now the little 1 carry slot worker is heading back through the swamp getting closer to the road and he will move faster right?, oh shit no this dev has repair roads when travelling. By the time he got to the road he was empty and had too turned back for more. This was going to take awhile to get any energy for spawning due to road repairs.

Eventually the pioneer shows and sees the worker on the closest mine and he decides of coarse to go to the furthest mine using an old long road around most of the swamp initially built by privateers. Damn it he will be empty due to repairs before he gets back.

Some time later there is enough energy to spawn what I thought would be a hauler, nope its a miner, ok well at least now the worker and pioneer will spend less time mining. Then another miner, maybe an upgrader cant remember, then a mineral miner.. wtf, wheres the hauler? All materials are going on the ground the containers at these sites have decayed. The worker and pioneer are back and forth between the miners picking up. Yes even the minerals are a long way off through the swamp. 

Finally a hauler and what does he do? Into the swamp to pickup :) this is why I went digging into the code found and changed the hauler picking to last in the list. I don't think this room would have recovered even with the 100000+ energy in storage and all links full that all creeps were ignoring due to pickup first, I had to destroy the extractor so they at least stopped having to pick up these minerals that were useless.

I have not yet found spawning order priorities for the rooms, but I do believe that the priority should be a hauler (with pickup last) a room will never collapse. something has to have pickup first and is better suited to workers.

I know I could have intervened earlier by manually spawning extra workers or I could have changed the code for the worker and pioneer to stop picking but I wanted to see if the room would recover without further intervention other then manually spawning the first worker. I gave it a long time before even destroying the extractor or changing the hauler picking order, without the hauler emptying the link the room was doomed. One good thing, I twice had an invader and they did prioritize getting energy to the towers :)

**Comment by cyberblast** [comment]
So there are a lot of points mentioned here :) 
I'm going to pick some of them: 
1. Links should be emptied prior to picking
2. Picking should be lowest prio for the hauler and higher for the worker
3. mineralMiner spawned without hauler
4. hauler should spawn first at all
5. where are spawning priorities defined

1. Links should be emptied prior to picking

Yes I absolutely agree. Thats why the hauler has it as highest priority. The reason why worker have picking as highest priority is: haulers are organizing energy distribution, but when there is an invader it will drop resources. The hauler should go on with its common tasks, the worker should go and get it. 
When you are dropmining, the worker should support in getting that energy home as good as possible. 

2. Picking should be lowest prio for the hauler 

When there is no container/link which requires to get emptied, the hauler should support in picking up energy. Thats very important during Dropmining. Also if there is no worker going to pick up. I agree, that picking shouldn't be the highest priority for the hauler, and it isn't. 

3. mineralMiner spawned without hauler

Hmm yes, I agree, that doesn't make any sense at all and needs to be fixed. Like only spawn mineralMiners when there is at least one hauler. and also reduce its priority. 

4. hauler should spawn first at all 

No, I don't think that makes any sense. Not in general. There may be a lot of cases, where there is no energy around. A worker is most versatile. But I agree that it should come quite soon. 
Currently it's only allowed to spawn a hauler, when there is at least one miner. We could maybe remove that rule... or maybe better change it to "if haulers+workers >= 2" or something like that... 

5. where are spawning priorities defined 

Well, it's not that easy. 
The order in which the spawn will check if a type can be spawned is defined in spawn.js. 
There are two arrays Spawn.priorityHigh and Spawn.priorityLow. The order of the items in these arrays is the order in which the spawn will try to spawn. First allowed type gets spawned. 
But thats the point - there are a lot of rules defining when it is allowed to spawn a certain type. Some of them are described in the wiki:
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/wiki/Settings-&-Tuning#2-how-to-adjust-population

**Comment by Krazyfuq** [comment]
You are correct and this is in the event of a room collapse, which we haven't seen for awhile and if that is indeed corrected this would be a non issue. Sorry, for some reason I thought haulers had mining as a low priority, just checked and they do not otherwise they could spawn first even for a new room. Once miners were up they would never mine again same as workers and pioneers.

**Comment by cyberblast** [comment]
hmm no. Also the fact that they have got a work part at all is quite new. Its only for "repair on driveby". I guess we can remove this one WORK part for "local" haulers and only add it for (future) remote haulers. I'm unsure about that or if we want to make such a distinction (local hauler, remote hauler)... 
Well that's why they don't have any action which requires a WORK part.

**Comment by Krazyfuq** [comment]
true thanks for your time

**Comment by cyberblast** [comment]
Thank you for pointing out this issue :)
