### ISSUE TITLE
Allow Miners and Haulers to Spawn at RCL 2

### ISSUE THREAD

**Issue by torin555** [ScreepsOCS/screeps.behaviour-action-pattern#428]
For this recent respawn I tried changing the spawn requirements of miners and haulers to RCL 2 instead of 3 and it's working much better. It allows for a constant supply of energy for the workers instead of making them mine it themselves. 

It's also brought to light the fact that using miners and haulers at RCL 2, you can spawn way more workers and get to RCL 4 much faster, since all that energy would just go to waste otherwise.

**Comment by cyberblast** [comment]
Sounds good :) 👍

**Comment by whardeman** [comment]
I love this. I've actually forced this through myself at times when I felt relying on tiny workers was going far to slowly. I'm still trying to expand as rapidly as possible (about to hit GCL 5), so I want the most fastest and most efficient RCL increase I can get as I move into more crowded territory.

Is there any active work being done for this change? What are the factors to be considered for making the change fit any room setup? Here's what I came up with...

- For haulers: source proximity (closer implies fewer required haulers) seems to be a key factor in spawning most efficient number. This includes
  - sources to Spawn
  - sources to Controller, and
  - sources to one another 
- For miners, always spawn 1/source, but respawn timing for soon-to-expire miners needs to take into account source proximity to Spawn.

**Comment by cyberblast** [comment]
> respawn timing for soon-to-expire miners needs to take into account source proximity to Spawn.

Yes there has been a recent change to improve that calculation. 
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/blob/dev/creep.behaviour.miner.js#L75

**Comment by chobobobo** [comment]
I'm a bit new to forks and pull requests, but I've forked the repo and this is the first change I will start working on.  Getting miners & haulers to start working is simple, I also plan to allow workers to continue mining a source as long as the miner has < 5 work parts so that we fully utilize the source [#545](https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/545) should provide us with more dynamic worker populations.

**Comment by karlthepagan** [comment]
I have a work in progress idea for this that you're welcome to take over @chobobobo !

https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/tree/feature/lowMiner

**Comment by chobobobo** [comment]
@karlthepagan ok, sounds good, so I should switch to that branch in my own fork, finish it and then submit a pull request right?

**Comment by karlthepagan** [comment]
sounds good! you can PR from your own repo until you get promoted into the org.

**Comment by torin555** [comment]
This hasn't been merged to dev yet so the issue shouldn't be closed

**Comment by chobobobo** [comment]
@torin555 oh yes, it was merged, but not into dev!

**Comment by karlthepagan** [comment]
The PR for dev is here - https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/639

**Comment by chobobobo** [comment]
Ok, this time it actually was merged!
