### ISSUE TITLE
Workers are sometimes unable to build walls / ramparts too close to the border

### ISSUE THREAD

**Issue by ESchuderer** [ScreepsOCS/screeps.behaviour-action-pattern#435]
Workers will somtimes infinitely switch between two rooms, instead of working on a construction site too close to the border.

For example:
https://screeps.com/a/#!/room/W72N28
X: 47 Y: 31

So far was unable to find the cause, looking at the following methods:

- Creep.drive (removing the leaveBorder() method didn't fix it, only using creep.moveTo without evade checks did neither)
- Room.validFields (Increasing position condition to 48 or 49 didn't fix it)

**Comment by cyberblast** [comment]
hmm strange. I wonder why it is going to the border (x:49) at all 😕

**Comment by ESchuderer** [comment]
Clearing memory and cache didn't help either, but today suddenly the workers behaved correctly again, maybe something with the room was bugged.

**Comment by Dasku** [comment]
Does this relate to #446 ? The construction sites my worker isn't constructing are 1 square away from the edge.

However my workers have built walls in other rooms (1 square from the edge as well). Seems to only be this 1 room for me which is affected.

**Comment by Dasku** [comment]
This does relate to #446 - if I create a construction site in the centre of the room, the worker goes to construct it. When I remove it and leave only the edge construction sites the worker fixed and began building again.

**Comment by Dasku** [comment]
![image](https://cloud.githubusercontent.com/assets/22677773/21772175/128be70c-d682-11e6-9020-7e3326ca1fb4.png)

After building a few more roads (in the red circle), the worker has now gone back to building the walls at the edge. No idea why or whats causing this.

**Comment by cyberblast** [comment]
When it's going back and forth, is it switching actions as well (showing activity bubble)? Which actions does it have assigned? is it switching EVERY tick? Which override files do you use?

**Comment by Dasku** [comment]
I don't think the bubble was changing. As its not doing it now I can't tell. 

The creep was moving 1 square each tick (X: 25->26->25...). Only non-standard files is the task.claim bits I was working on. The creep always collected 50% energy from the container before it started to happen. 

Going back to standard files today, with changes to flags etc I'll restart the claim.task from scratch. Will monitor and update if happens again.

**Comment by cyberblast** [comment]
Is this still occurring?

**Comment by karlthepagan** [comment]
Yes, I've attempted to resolve this, see branch bug/borderStuck.

Sometimes however I think that it becomes a logical loop of a creep moving into the next room and determining the best path is to go back the way it came (happens to my claimers going from W79S51 to the right)

**Comment by cyberblast** [comment]
hmm, the leaveBorder code can't be the problem.It only gets called if there has been an other problem before, to get the creep off the border if it's currently left there...

**Comment by karlthepagan** [comment]
Ah no, I just noticed I could re-use it as a possible solution.

I'm calling my new leaveBorder at the begging of creep.run, and I ignore the finding if there's a planned movement (logging when it mismatches).

**Comment by karlthepagan** [comment]
After I watched a bunch of creeps print "moving as expected" over and over again I only have two scenarios left to examine
* if the path terminates at the border and this causes a problem (no observations yet)
* if there's a logical loop where the behaviour / action combination results in the creep reversing its direction (much harder to triage)

**Comment by cyberblast** [comment]
Well, the point I don't get is: there is a construction site near that border. Why does the creep leave at all? I mean, yes I can imagine routes where the shortest way may be through an other room. But as far as I know that wasn't the case. So where and why is that creep going?

**Comment by chobobobo** [comment]
I believe this was resolved when we moved to Traveler.js https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/751 I have not seen it since.
