### ISSUE TITLE
Setup queue refactor

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#453]
I would like to propose a change to the Creep.Setup API to make it more extensible and to allow customizations based on RCL and player strategy.

Currently setup queuing is managed by Spawn.extend and usually extended via Global.extend (which explains why global must be extended after all built-ins)

in viral.global.js:
```
        Spawn.priorityLow.push(Creep.setup.mySetup1);
        Spawn.priorityHigh.push(Creep.setup.mySetup2);
```

I propose moving these into Creep.Setup like this:

in creep.setup.mysetup2.js:
```
setup.RCL = {
    1: {
        // ...
        highPriority: 100, // must be "truthy"
    },
// ...
```

in creep.setup.mysetup1.js:
```
setup.RCL = {
    1: {
        // ...
        lowPriority: 50,
    },
// ...
```

This is cached into 2 accessors which will function similar to the current logic:
Room.prototype.setupQueueHigh
Room.prototype.setupQueueLow

These lists will be sorted each time they are accessed and the sort cached per-room, but access to these lists will also be lazy so that only the high priority queue will be created for most rooms.

**Comment by whardeman** [comment]
I think I understand what you're doing here, but I do have questions that I think will move the discussion forward: 
-How will this effect my management of rooms at a practical level?
-Does this change bring a new efficiency to the game for anyone using OCS code, or will this only impact me if I choose to customize setups?
-For the uninitiated player or those with less programming experience, do you expect the the net benefit to be positive, negative or neutral?

**Comment by karlthepagan** [comment]
Work in progress: https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/tree/change/setupQueue

> How will this effect my management of rooms at a practical level?

For example, as your empire becomes larger and more distributed you can implement viral.creep.setup.worker to de-prioritize workers (entirely) and instead assign pioneers to travel and bring your RCL up. That example might also be implemented using per-GCL logic, but I think that's a larger investment in automation.

As a second example, at RCL8 you might choose to relocate upgraders to the low priority queue.

> Does this change bring a new efficiency to the game for anyone using OCS code, or will this only impact me if I choose to customize setups?

There is a trivial decrease in efficiency. Per room where `n` is the number of creep setups: `O(n log n)` added to today's `O(3 * n)`. This is because `_.some(Spawn.priorityHigh, probe)` returns immediately when a match is found. Because `n` is always very small this shouldn't be a concern.

When you customize setups I believe you will see less complexity in your implementation.

> For the uninitiated player or those with less programming experience, do you expect the the net benefit to be positive, negative or neutral?

Players struggling to understand the spawn priorities will have access to the accessor functions which will expose the internal decisions. I think it will be a net benefit for all users.

**Comment by karlthepagan** [comment]
I've added a memoize around the setup queue so that is only calculated once per  controller level.

**Comment by karlthepagan** [comment]
That means that at high GCL there will be effectively no runtime cost.

**Comment by whardeman** [comment]
@karlthepagan Good detail. Thanks for all that.

**Comment by karlthepagan** [comment]
This has been abandoned in favor of Task spawning.
