### ISSUE TITLE
Requires, extends, and globals should be done outside loop to save CPU.

### ISSUE THREAD

**Issue by pandabear41** [ScreepsOCS/screeps.behaviour-action-pattern#473]
As the title states we should put requires, extends, and globals outside of the loop so they don't get called every tick. This saves on tons of CPU. Before having the code in the loop I was using 8-12 CPU. After moving the code to outside the loop I was using 3-7 CPU. 

> First tick after saving code [3:09:42 PM]Time: 43.820839
> [3:09:44 PM]Time: 2.189336
> [3:09:47 PM]Time: 2.009665
> [3:09:49 PM]Time: 2.165806
> [3:09:52 PM]Time: 1.540165
> [3:09:54 PM]Time: 1.891563
> [3:09:57 PM]Time: 1.9866970000000002
> [3:09:59 PM]Time: 1.636202
> [3:10:02 PM]Time: 2.548996
> [3:10:04 PM]Time: 2.5756580000000002
> [3:10:22 PM]Time: 6.981793
> [3:10:24 PM]Time: 4.12761
> [3:10:27 PM]Time: 3.248144
> [3:10:29 PM]Time: 4.682407
> [3:10:32 PM]Time: 3.27851
> [3:10:34 PM]Time: 2.717758
> [3:10:37 PM]Time: 3.7689660000000003
> [3:10:39 PM]Time: 2.0775449999999998
> [3:10:42 PM]Time: 2.919263
> [3:10:44 PM]Time: 3.093337
> [3:10:47 PM]Time: 2.888508
> [3:10:49 PM]Time: 3.097371
> [3:10:52 PM]Time: 3.0346130000000002
> [3:10:54 PM]Time: 2.728107
> [3:10:57 PM]Time: 2.972725
> [3:10:59 PM]Time: 3.626682
> [3:11:02 PM]Time: 3.418885
> [3:11:22 PM]Time: 11.145610999999999
> [3:11:24 PM]Time: 1.57171
> [3:11:27 PM]Time: 3.136322
> [3:11:29 PM]Time: 5.144436
> [3:11:32 PM]Time: 3.734363
> [3:11:34 PM]Time: 3.762892
> [3:11:37 PM]Time: 3.241085
> [3:11:39 PM]Time: 3.705381
> [3:11:42 PM]Time: 5.820296
> [3:11:44 PM]Time: 3.0947069999999997
> [3:11:47 PM]Time: 3.7257740000000004
> [3:11:49 PM]Time: 1.9626379999999999
> [3:11:52 PM]Time: 1.674601
> [3:11:54 PM]Time: 1.9640630000000001
> [3:11:57 PM]Time: 2.070341
> [3:11:59 PM]Time: 1.651387
> [3:12:02 PM]Time: 3.024368
> [3:12:04 PM]Time: 3.367321
> [3:12:22 PM]Time: 2.468998
> [3:12:24 PM]Time: 2.8003600000000004
> [3:12:27 PM]Time: 2.542935
> [3:12:29 PM]Time: 8.021970000000001
> [3:12:32 PM]Time: 1.817733
> [3:12:34 PM]Time: 9.10115
> [3:12:37 PM]Time: 3.182086
> [3:12:39 PM]Time: 2.179741
> [3:12:42 PM]Time: 2.61679
> [3:12:44 PM]Time: 3.779075
> [3:12:47 PM]Time: 2.11043
> [3:12:49 PM]Time: 3.335519
> [3:12:52 PM]Time: 2.90464
> [3:12:54 PM]Time: 1.3648230000000001
> [3:12:57 PM]Time: 3.290857
> [3:12:59 PM]Time: 1.827061
> [3:13:02 PM]Time: 2.4672799999999997
> [3:13:04 PM]Time: 1.927806
> [3:13:22 PM]Time: 18.782649
> [3:13:24 PM]Time: 3.3780520000000003
> [3:13:27 PM]Time: 1.6941599999999999
> [3:13:29 PM]Time: 1.471915
> [3:13:32 PM]Time: 1.925383
> [3:13:34 PM]Time: 2.030947
> [3:13:37 PM]Time: 1.802832
> [3:13:39 PM]Time: 1.5845040000000001
> [3:13:42 PM]Time: 1.598177
> [3:13:44 PM]Time: 1.8864450000000001
> [3:13:47 PM]Time: 2.8713450000000003
> [3:13:49 PM]Time: 2.368931
> [3:13:52 PM]Time: 1.70074
> [3:13:54 PM]Time: 2.116803
> [3:13:57 PM]Time: 1.483103
> [3:13:59 PM]Time: 2.198212
> [3:14:02 PM]Time: 1.627645
> [3:14:04 PM]Time: 3.1493800000000003
> [3:14:22 PM]Time: 2.77208
> [3:14:24 PM]Time: 3.2207440000000003
> [3:14:27 PM]Time: 3.148127
> [3:14:29 PM]Time: 3.76452
> [3:14:32 PM]Time: 2.4996370000000003
> [3:14:34 PM]Time: 1.9647929999999998
> [3:14:37 PM]Time: 3.682454
> [3:14:39 PM]Time: 3.7783670000000003
> [3:14:42 PM]Time: 2.815738
> [3:14:44 PM]Time: 3.22217
> [3:14:47 PM]Time: 10.69418
> [3:14:49 PM]Time: 1.5433299999999999

Whenever a script changes via grunt task or update in gui or web, the code before the main loop.
Source: http://support.screeps.com/hc/en-us/articles/204825672-New-main-loop-architecture
https://www.reddit.com/r/screeps/comments/50u1lx/using_global_variable_like_an_enum/d76zble/

**Comment by pandabear41** [comment]
I put the time capture from lines 4 and 129 in main.js

On line 4:
let s = Game.cpu.getUsed();

On line 129:
let e = Game.cpu.getUsed();
console.log("Time", e-s);

**Comment by karlthepagan** [comment]
Notable exception: `parameter` should be re-assigned to global every tick.

**Comment by karlthepagan** [comment]
For testing and to facilitate live editing IMO this should be optional.

**Comment by cyberblast** [comment]
hmm. yes we've had that outside of the main loop in the beginning (i's quite a time ago). 
But then we've had some issues with caching, and calling it within loop is the most reliable and easy solution. 
But I think we do have some improvements now, we can try to put some outside again. Please just keep an eye on strange behaviour.

**Comment by webremote** [comment]
As long as the `load` function is used, it should be reliable in or outside the loop. The `Memory` is always up to date.... Or were there specific issues?

**Comment by cyberblast** [comment]
yes, when saving data to the modules and using it as an object cache. That data will only be the same on 1 server. But there are many of them. 

You can try it yourself. simply declare a variable outside the main loop. Change it manually (console) and log its value each tick. Its changed value will be there sometimes, and sometimes not. Depending on which server you are on (which you don't know). 

The same is true for storing values in server objects (like room or creep).

**Comment by webremote** [comment]
> Optimized new main loop caching. The global object must be fully cached in 20-30 ticks after commiting a script.
http://support.screeps.com/hc/en-us/articles/204825672-New-main-loop-architecture

You're right, didn't realize this until i noticed those "weird" results. The Memory object doesn't seem to be available either outside the main loop, so I understand a bit more now.

My preferred solution would be to use `grunt` and `webpack` to _generate_ the combined files instead. It would solve a lot of problems with injections/`Memory.modules` not working (properly/as expected).

**Comment by pandabear41** [comment]
> @webremote: My preferred solution would be to use grunt and webpack to generate the combined files instead.

That would fix the CPU problem of requires, but setting the globals and extensions every tick is really unneeded.

**Comment by pandabear41** [comment]
On a side note, I have been running with lines 12-128 outside of main loop for 6 hours now with no errors or issues.

**Comment by webremote** [comment]
@pandabear41 well, the current webpack doesn't work due to the injection methods so it would need a refactor anyway. i do think it is possible to generate a webpack that executes something outside the main loop, i've seen it before. i'm just not sure how to get that done in the current setup 😛

**Comment by cyberblast** [comment]
hmm, there is a problem with the event system. 
I moved lines 12-128 outside the loop as well. But the event handlers subscribe each tick, causing to trigger them multiple times: 
![image](https://cloud.githubusercontent.com/assets/20269868/21964356/8f140fa8-db4a-11e6-8265-2129db085bfd.png)

**Comment by cyberblast** [comment]
I'd like to close this one. This issue continues at #488
