### ISSUE TITLE
2017-1-13 UNSTABLE? dev

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#479]
My haulers and workers stopped refilling spawns and extensions.

I've created the tag `stable-2017-1-13` for people to use until we can revert or fix dev.

**Comment by whardeman** [comment]
I don't know if this is helpful, but I'm running dev with very minimal overrides and I'm not experiencing this kind of issue.

**Comment by karlthepagan** [comment]
I've disabled my overrides, but I don't know if I will quickly see a repro of this situation: https://screeps.com/a/#!/history/W74S57?t=16726960

**Comment by karlthepagan** [comment]
I believe I've resolved this. I'll delete my tag now :P
