### ISSUE TITLE
trace debugging

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#480]
Demo forming up here:
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/tree/debuggingWithTraces

problem: you want to add debugging but it's a lot of effort to track down all the places you need to see

solution: use objects like where clauses:

Logging statement in code (creep.js:158)
```
if( TRACE ) trace('creep',{creepName:this.name,creep:'behaviour'}, behaviour && behaviour.name);
```

Querying this in the game:
```
Memory.debugTrace.creep = 'behaviour'; // prints what behaviour the creep selects
Memory.debugTrace.behaviour = true; // prints ALL internal behaviour logic for all creeps
Memory.debugTrace.creepName = 'miner-850-1'; // restricts match to just this miner
```

So basically the conditions which are present in the log statement must match what's set in `Memory.debugTrace` or they must be absent.

Still working this out in order to gain better insight into spawning.

**Comment by karlthepagan** [comment]
rebased onto the refactor

**Comment by karlthepagan** [comment]
I think #490 is ready.

**Comment by cyberblast** [comment]
@karlthepagan can you please add a wiki page describing how to configure trace filters in Memory.debugTrace?

**Comment by karlthepagan** [comment]
Very basic docs started here: https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/wiki/Log-filtering-using-Memory.debugTrace

**Comment by karlthepagan** [comment]
This is implemented.
