### ISSUE TITLE
Setting up a clean main workflow

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#488]
The task system is based upon events. Triggering events while the environment gets evaluated is a bad idea, as not all information is prepared. 
The current main requires a restructuring. There should be clear and distinct stages. 

**Outside main loop:** 

1. Define module loading/injection framework
2. Initialization of global and parameters
3. Load modules
4. Extend server objects

**Inside main loop:** 

5. Ensure parameters
6. Flush & prepare cache
7. Analyze Environment
8. Register event hooks
9. Execution
10. Post processing

**Functions in main for custom overrides** 

* mainInjection.extend (4)
* mainInjection.flush (6)
* mainInjection.analyze (7)
* mainInjection.register (8)
* mainInjection.execute (9)
* mainInjection.cleanup (10)

*global.custom will be deprecated* 

Working on it at [change/main](https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/compare/change/main). / PR: #533

**Comment by whardeman** [comment]
I, for one, welcome our new task-based overlords.

**Comment by cyberblast** [comment]
Please note: there is a new module for custom main flow injections via overrides: mainInjection
you should use mainInjection.extend instead of global.extend and one of the other methods instead of global.custom (depending on purpose/timing).
