### ISSUE TITLE
Pioneer predicted spawning

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#497]
I had a pioneer which died in an enemy room, when it died I got the following error over and over. 

TypeError: Cannot read property 'homeRoom' of undefined
    at validateRunning (task.pioneer:145:57)
    at Array.forEach (native)
    at Object.handleCreepDied (task.pioneer:150:28)
    at Creep.died.on.name (task.pioneer:14:45)
    at handlers.slice.forEach.h (global:25:57)
    at Array.forEach (native)
    at LiteEvent.trigger (global:25:44)
    at register (population:163:28)

Which is part of the predicted spawning

     let validateRunning = o => {
                let creep = Game.creeps[o];
                // invalidate old creeps for predicted spawning
                // TODO: better distance calculation
                let prediction;
                if( creep.data && creep.data.predictedRenewal ) prediction = creep.data.predictedRenewal;
                else if( creep.data && creep.data.spawningTime ) prediction = (creep.data.spawningTime + (routeRange(creep.data.homeRoom, flag.pos.roomName)*50));
                else prediction = (routeRange(creep.data.homeRoom, flag.pos.roomName)+1) * 50;
                if( creep && creep.name != name && creep.ticksToLive > prediction ) {
                    running.push(o);
                }
            };

But the flags did not exist anymore when they died, so they really shouldn't be expected to respawn.

And does the creep.data still exist after a creep is dead?

**Comment by cyberblast** [comment]
yes. the Creep.died event triggers before the creeps memory is deleted.

**Comment by Dasku** [comment]
#498 should fix this.
