### ISSUE TITLE
mineralMiners should utilise multiple containers

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#502]
![image](https://cloud.githubusercontent.com/assets/22677773/21963361/7289c13e-db31-11e6-9ca5-369ab0196a73.png)

Instead of using the second container provided (_the full container was actually added second_) the mineralMiner instead drop mines which loses minerals. This mine is a "long" trip for a home room so often the container gets full and I was hoping a second container would stop the waste.

**Comment by Dasku** [comment]
I suppose this wont be as much of an issue if I can spare a link for the mineral mine at RCL8..

**Comment by cyberblast** [comment]
also, the mineralMiner shouldn't try to use links (creep.behaviour.mineralMiner.js line 75) 
(as links can only take energy)

**Comment by karlthepagan** [comment]
Also if there is a non-full container underneath the miner then don't waste 0.2 CPU on the deposit, the overflow will get collected.

**Comment by Dasku** [comment]
Wouldn't the minder then select the container it was stood on as its deposit container and still just drop mine once its full?

**Comment by Dasku** [comment]
This should probably fix itself now we spawn an additional hauler when mineral miner is action.
