### ISSUE TITLE
task.reserve configuration to ignore select mined rooms

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#508]
I think that ROOM_ROUTE_COST > 1 should place reservers in the low-priority queue. ROOM_ROUTE_COST > 10 should not try to reserve the room.

I won't use DEFENSE_BLACKLIST for this because that might have other conflicting uses.

Changing the route cost slightly means that creeps will try to move around the room tho so maybe there should be a separate setting.

**Comment by Dasku** [comment]
I think this should probably be an option somehow too. It would be easy enough to add a "ignore reserving this room" flag so people don't need to manually change their memory.

**Comment by karlthepagan** [comment]
I am going to close this after improved remote mining and the changes in #668 reserver throttling
