### ISSUE TITLE
Pioneer Improvement thread 

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#517]
Ideas below, will add to this list:

1) Pioneers create the spawn on their own flag, regardless of if they are spawn pioneers or additional pioneers (from green/red flag). We could simply only build on green/white flag or:
       * Increase number of pioneers sent from spawn flag from 4-5/6? (so green/red flag no longer needed for new rooms) (I think 4 is enough but it seems most people send more with green/red)
       * Don't delete pioneer spawn flag when spawn completes, instead leave it until RCL4 and mining starts (reduce to 3 if/when mining requirements reduce to RCL3)
              * Reduce number of pioneers after spawn finished to 2 until RCL3-4 is reached (this is not always a good move if its a hard trip to the new room via SK rooms so deleting the flag after spawn completes is still possible)

2) Additional Pioneers (Green/Red) could then be redeveloped a bit and be used as a dead room revival mechanism #493 triggered from a task maybe?

Not sure what else pioneers *need* to do so this could be a quick change.

**Comment by cyberblast** [comment]
I think the easiest and most flexible solution would be to ONLY use 1 flag for the pioneers (spawning 1 each). 
An additional manually set flag marks the position for the first spawn. 

Flag colors could stay the same...

**Comment by torin555** [comment]
+1 for having green/red be used to spawn creeps for room revival

**Comment by torin555** [comment]
One issue we need to address for room revival with pioneers is to never spawn the pioneer in the room with the flag. There's never a reason for that to be done.

**Comment by torin555** [comment]
@cyberblast I think the auto flag placement is bugged, it's placing them in rooms that aren't dying.

**Comment by cyberblast** [comment]
hmm reproducible?

**Comment by torin555** [comment]
No clue why it's happening, but it's happened in two of my rooms

**Comment by cyberblast** [comment]
strange. 

I forgot flushing the cached property. But I don't think it can be the reason. Anything special happened to both rooms when they got the flag?

**Comment by torin555** [comment]
I'm not sure, wasn't watching the rooms at the time. I'll keep an eye out for it to happen more.. If it doesn't happen again for the next couple days I think we can just say it was a freak occurrence.

**Comment by torin555** [comment]
Nope still happening, it's happened to two more of my rooms. Still no idea why, it seems totally random.

**Comment by karlthepagan** [comment]
I have no idea how but I'm seeing this now. I'll triage when I can.

**Comment by cyberblast** [comment]
I got a flag as well, but there was no hauler, no worker & no pioneer present, so it's reasonable. 
Changing the algorithm: 
1. Try to spawn a worker
2. only place a flag if that is not possible

**Comment by torin555** [comment]
I'm definitely getting flags when at least one of these is present. I'm getting them in fully functioning RCL 7 rooms

**Comment by cyberblast** [comment]
I'm getting them as well quite often. 
I think at least one reason is, that sometimes there are 0 workers around, and it will not spawn any, because it is not intended anymore to always have at least one. 
When the hauler dies, there may be a very short time when there is no worker and no hauler. This will trigger "Room.collapsed". 
PR #589 should prevent flag placement (it will still spawn a worker). 

Maybe we should also implement a delay, like "if there is no worker/hauler/pioneer for 25 ticks"...

**Comment by forkmantis** [comment]
Oh.  I saw that this morning on a private server.  I thought I was going crazy and had put the flag there for some reason.

**Comment by OverlordQ** [comment]
I'm not liking these changes. It seems to break the 'Drop a green/green where you want the spawn to be' behavior where everything is handled automatically.

If you drop a 'green/green' once that room is claimed it gets turned into a green/white, but then nothing happens. Some 'green/red' flag gets put at 25,25, and it tries putting the spawn there.
