### ISSUE TITLE
Part arrangement with new spawning system

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#521]
Currently only the 1 heal part last respects part arrangement (or its muddled up). Currently hopper is spawning with HEAL first, then MOVE, then all TOUGH with 1 HEAL last.

As the multibody is mixed, it must be being ordered another way.
   multiBody: [TOUGH, MOVE, TOUGH, MOVE, MOVE, HEAL],

**Comment by cyberblast** [comment]
hmm. how does its body look like? My current creeps look fine ...

**Comment by Dasku** [comment]
It was HEAL HEAL HEAL, MOVE, MOVE MOVE MOVE MOVE MOVE, TOUGH, TOUGH  TOUGH, TOUGH  TOUGH, TOUGH, HEAL

Also noticed there is no max range so they are spawning from all over the place now and the flag isn't even there anymore

**Comment by Dasku** [comment]
![image](https://cloud.githubusercontent.com/assets/22677773/21998134/f44b11ce-dc2a-11e6-9bae-ceed309a2e86.png)

**Comment by cyberblast** [comment]
strange :/ your other creeps as well? 
part sort order is: [TOUGH, CLAIM, WORK, CARRY, ATTACK, RANGED_ATTACK, HEAL, MOVE] 
(plus 1 heal moved to the end...)

**Comment by whardeman** [comment]
@Dasku Is the code you're running checked in? Please link to correct source if so and I'll take a look.

**Comment by Dasku** [comment]
erm no my code could be a bit of a mess at the moment, let me refresh now all fixes are in and ill reopen if it persists
