### ISSUE TITLE
Checking room controller before spawning second Reserver

### ISSUE THREAD

**Issue by damintsew** [ScreepsOCS/screeps.behaviour-action-pattern#522]
Fix from Reserving Improvement Thread 'https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/issues/515'

When queuing a second reserver, check the controller to ensure there is space for 2 reserver's. If not, delete the queued reserver in low queue when spawning from Medium.

**Comment by cyberblast** [comment]
Not implemented in that way. 
see comments in #523 & implementation in #555 instead.
