### ISSUE TITLE
assigning actions usually does not clear path or target selection

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#529]
for example
`Creep.action.harvesting.assign(Game.creeps['worker-200-2'], Game.getObjectById('guid of a mine'))`

this should always put the worker on that mine, selecting an open square to mine in

the creep should immediately discard its path and move to the new target

**Comment by cyberblast** [comment]
Yes. it's commonly done within the behaviour, after a new action has been assigned. But I agree, this should be moved into action.assign.

**Comment by cyberblast** [comment]
implemented with #556
