### ISSUE TITLE
behaviour.mining - a miner with no CARRY part must select a container mining spot

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#532]
currently a 5 work 1 move miner (max at RCL2) will shift to sit next to another energy holder (like a spawn) and ignore the container

**Comment by karlthepagan** [comment]
looks like a problem in the base behaviour, i thought it was in the task

**Comment by karlthepagan** [comment]
also determineTarget should account for travel vs TTL of any assigned miners

I'll take a look at these in the next hour

**Comment by cyberblast** [comment]
we don't build miner without carry. 
Personally I prefer mining into links (without any container at the source), at least at home. 
Unsure if it is that important.

**Comment by karlthepagan** [comment]
that should be up to the user

this is critical for an efficient respawn

**Comment by chobobobo** [comment]
resolved by https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1030
