### ISSUE TITLE
Creeps don't feed spawn when others are recycling.

### ISSUE THREAD

**Issue by pandabear41** [ScreepsOCS/screeps.behaviour-action-pattern#538]
Just had a room almost die off since creeps don't feed spawn due to recycling creeps targeting the spawn. [creep.Action.js#L42](https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/blob/dev/creep.Action.js#L42)

Was thinking of replacing the current code
`return (this.maxPerTarget === Infinity || !target.targetOf || target.targetOf.length < this.maxPerTarget);`
with
`return (this.maxPerTarget === Infinity || !target.targetOf || (creep.type ? _.filter(target.targetOf, t => t.type == creep.type).length : target.targetOf.length) < this.maxPerTarget);`
but then workers and haulers can feed the same target. The same goes with just filtering out creeps with the recycling action, then when a creep is repairing spawn or a tower other creeps can't be feeding or fueling it.

**Comment by cyberblast** [comment]
I like your approach in #518. 
How about implementing that in the base like 
`(!target.targetOf || _.filter(target.targetOf, {'actionName': this.name}).length < this.maxPerTarget));`

**Comment by pandabear41** [comment]
I honestly forgot I did #518.

**Comment by pandabear41** [comment]
Fixed with #544
