### ISSUE TITLE
Pioneer spawn issue

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#560]
How does range work with the new spawn system? I cant't see the max range or how to change it.

I took a new room last night, after it was claimed it sent 1 pioneer, then no more spawned. I manually spawned a few to get the spawn finished and the room started. 

Not sure if this is a range issue, or if the changes to the spawn system mean I need to change the pioneer task to ensure tasks are picked up and the pioneers are spawned correctly, 

The flags are working and memory is being set correctly but the creep is not passed into a spawn queue from what I can tell.

**Comment by Dasku** [comment]
Also had a RCL6 room die, after reviving it just now the first creep to spawn was a pioneer so they are being queued I think. But this room is about 10 range from the room I took last night.

**Comment by Dasku** [comment]
Looks like they all got stuck in the queue of 1 room (the one that died)
![image](https://cloud.githubusercontent.com/assets/22677773/22103406/ec61d3da-de32-11e6-8154-ee8364b3e8cb.png)

**Comment by karlthepagan** [comment]
I caught this one and started a fix. The pioneers try to spawn in the destination room.

The solution involves migrating to the new room.findspawn function.

**Comment by Dasku** [comment]
Is this fixed now? (pioneers have been working fine for me recently)

**Comment by karlthepagan** [comment]
👍 works great for me, and using #858 this is really helpful to a new room
