### ISSUE TITLE
Let minerals move from storage to terminal

### ISSUE THREAD

**Issue by webremote** [ScreepsOCS/screeps.behaviour-action-pattern#584]
![image](https://cloud.githubusercontent.com/assets/15063100/22174272/984c8ae8-dfda-11e6-87dc-9aad67378124.png)

There's currently no way of transferring minerals from storage to terminal. The `O` resources were bought through the terminal and were then moved to storage: not exactly expected behaviour and it can't be changed.

**Comment by cyberblast** [comment]
Requires a resource distribution strategy: #338

**Comment by karlthepagan** [comment]
as a workaround you can set the room's resourceType to the one you want to sell.
