### ISSUE TITLE
How to defeat controller

### ISSUE THREAD

**Issue by Krazyfuq** [ScreepsOCS/screeps.behaviour-action-pattern#586]
Last night I finished invading another room, before logging out I placed a red/cyan flag and only one atk-contr creep was spawned no replacements when it died, though the flag remained. is this intended? 
Em I doing something wrong do I need another type flag?
Right now I am placing multiple red/cyan flags and replacing the flags as the creeps die too respawn these creeps.
I also hoped to take advantage of the energy sources by placing red/green flag but all that happened was 3 reservers were spawned who then sat by the controller doing nothing.

**Comment by cyberblast** [comment]
Ok, I see 2 different issues here. 

1. The controller-attacker state didn't get updated when it died. It may still have it registered somewhere in its memory. 
2. Reserving should always check if the controller is owned or reserved by an other player (at least when there is sight).

**Comment by cyberblast** [comment]
Closing this one. 
Follow up in sub issues #587 & #588
