### ISSUE TITLE
Don't send reservers in owned rooms

### ISSUE THREAD

**Issue by cyberblast** [ScreepsOCS/screeps.behaviour-action-pattern#588]
Reserving should always check if the controller is owned or reserved by an other player (at least when there is sight). 
It sent reservers to a room owned by an other player.

Follow up on #586

**Comment by whardeman** [comment]
What if we just check whether the room is owned at all? That's good enough to know a reserver shouldn't be spawned right?

**Comment by cyberblast** [comment]
agreed. + if it is reserved by an other player. 
But it's still only possible with sight.

**Comment by whardeman** [comment]
Resolved by #592
