### ISSUE TITLE
Broken dropped resource logic.

### ISSUE THREAD

**Issue by jisaf** [ScreepsOCS/screeps.behaviour-action-pattern#624]
If a container fills, and a miner (mineral or energy) starts drop mining, a hauler or worker will go pick it up. Great.

But, if the creep isn't full, it should then look for a nearby container or link to pull from to ensure full capacity.

I just had a worker walk all the way over to the corner of my room, pick up 34 minerals (out of 450 capacity), ignore the full container right next to it, and then go to deposit it in storage.

When it finishes depositing in storage, there's now new drop-mined minerals because the container is still full, so it goes to pick them up. 

My 1600 weight worker is now stuck in a never ending loop of shuttling ~15 minerals at a time from the ground, instead of building the terminal or labs that are waiting to be built.

**Comment by karlthepagan** [comment]
Reported in #546
