### ISSUE TITLE
Hoppers can become Healers

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#664]
Once healers are working properly (currently they cannot invade), I would like a way for hoppers to convert to healers and support an attack once the towers have been drained.  
I propose, Red/Cyan flag to convert a hopper into a healer who tries to move to the flag room and then work as a healer within that room.  If there are no creeps to heal, it returns to hopper behaviour.

**Comment by karlthepagan** [comment]
Move this to internal.
