### ISSUE TITLE
Broken Source

### ISSUE THREAD

**Issue by torin555** [ScreepsOCS/screeps.behaviour-action-pattern#681]
One of my sources seems to be totally broken. I've cleared room memory, suicided the miners, and destroyed the container. (It's being rebuilt but the room doesn't have enough energy to finish it.)
![screenshot_19](https://cloud.githubusercontent.com/assets/2602862/22702276/67eca360-ed1d-11e6-9bc9-46bb8bf828c5.png)

**Comment by karlthepagan** [comment]
Difficulty: novice to intermediate

Adding trace logging around sources would be very helpful. Don't worry about it being perfect, just make it so that there's an id=source.id entry in the `entityWhere`

**Comment by torin555** [comment]
@karlthepagan Could it possibly have to do with the location of the terminal? That's the only thing that's changed since this started, and it's 2 spaces away from the source. Could it be thinking the terminal is a container?

**Comment by whardeman** [comment]
@torin555 That's at least possible. I'd even say likely given the circumstantial evidence. Does it appear in the container room.structures.container.in list?

**Comment by torin555** [comment]
@whardeman Where would I find that?

**Comment by whardeman** [comment]
@torin555 Assuming you know how to get the object id of the terminal, copy it and from console, try running the following:

`Game.getObjectById('objectIDOfTerminal').source`

**Comment by torin555** [comment]
@whardeman undefined, guess that rules that option out... But it's the only thing that makes sense and this isn't happening in any of my other rooms...

**Comment by whardeman** [comment]
@karlthepagan Try one more thing: Grab the object id of the source itself, and run...

`Game.getObjectById('sourceID').container`

**Comment by torin555** [comment]
@whardeman Ahah! `[structure (terminal) #5899dcc6631995a3780c7484]`

**Comment by whardeman** [comment]
Now we just have to debug that in room.js.

**Comment by whardeman** [comment]
Here's the offending logic in room.js:
```
        if( this.terminal ) {
            let source = this.terminal.pos.findInRange(this.sources, 2);
```
The defect here, obviously, is that a Terminal can be with `range <= 2` but not be adjacent to any spot in `room.sourceAccessibleFields` which would be required for a miner to use the Terminal as its container.

**Comment by whardeman** [comment]
Just pushed the above quick-n-dirty branch with one commit that potentially resolves this specific issue with the terminal. It can be extended to other structure/position mappings, or rewritten by someone with more time.

I'll need people to look at it and make it better probably. It has NOT been tested, though that can probably be done in sim.
