### ISSUE TITLE
remoteHaulers being set to workers

### ISSUE THREAD

**Issue by OverlordQ** [ScreepsOCS/screeps.behaviour-action-pattern#698]
Somehow my remoteHaulers are getting their creepType set to 'worker' so they get confused, load up on energy, and try to start building with their 1 WORK part, effectively spending their entire lifetime trying to build the same object.

They should fall back to hauling not working.

**Comment by chobobobo** [comment]
@logxen I think it's possible what happened here was related to #593, if their type has been set to worker, that means their population entry was missing for whatever reason and it defaulted.  I have seen this infrequently as well and currently the only fix is to manually change their creepType back to remoteHauler.

**Comment by karlthepagan** [comment]
related to #593 - dying creep workflow

**Comment by OverlordQ** [comment]
Yeah,  likely issue.
