### ISSUE TITLE
Release Candidate CPU baselining

### ISSUE THREAD

**Issue by whardeman** [ScreepsOCS/screeps.behaviour-action-pattern#700]
I'm starting this issue mostly for myself, but to also keep track in a public place the performance of  release candidate `2017-2-rc1` in CPU for GCL7.

I started with 7 rooms ranging from RC8 down to RC5. Zero remote mining rooms. I'll be adding remote mining rooms slowly and tracking CPU as we go.

Initial readings range between 25-40 CPU.

After 1 mining room, CPU hovers between 35-45 with occasional spikes up to 60. (Good chance spikes are due to several creeps at once all trying repath, especially when routes cover long distances.)

**Comment by whardeman** [comment]
Holding very steady.

RM Rooms: 1
Avg CPU: 40 
Spikes: Rare, up to 70

**Comment by whardeman** [comment]
I'm going to ramp this up a little faster now as it appears to be handling things fine.

RM Rooms: 4
Avg CPU: 50
Spikes: Uncommon, up to 115 (this has to be rooms recaching objects)

**Comment by whardeman** [comment]
RM Rooms: 8
Avg CPU: 55
Spikes: Occasional, typically 115, up to 130

**Comment by whardeman** [comment]
RM Rooms: 11
Avg CPU: 70
Spikes: Occasional, typically ~120, up to 141

I also set REMOTE_WORKER_MULTIPLIER:1 during this window.

**Comment by karlthepagan** [comment]
related to #318
