### ISSUE TITLE
Master 2017-2 Release Candidate

### ISSUE THREAD

**Issue by karlthepagan** [ScreepsOCS/screeps.behaviour-action-pattern#708]
Current branch: `2017-2-rc1`

Please comment with any testing results.

**Comment by Dasku** [comment]
2017-2-rc1?

**Comment by Dasku** [comment]
Run for 6 hours, attacked and killed a room, created new mining rooms, robbed extensions and the storage is half way down (still ongoing), seems very stable, not seen any errors in that time.

**Comment by whardeman** [comment]
Only major issue I've encountered: Remote miners are being sent to rooms to take over when the previous miner has not yet expired (predictedRenewal?) but the 2nd miner border-thrashes and never goes to the source.

**Comment by Dasku** [comment]
Had this on 22 hours now, also taken a new room, used priavteers and pioneers. The robbing has completed correctly. Did look around for edge creeps @whardeman suggested but couldn't find anything.

Feels like a good stable code position to me, all features I've been able to test are working well 👍 

Going back to try out some canary stuff now though.

**Comment by karlthepagan** [comment]
This has been released. - version 0.6.1
