### ISSUE TITLE
Whitelist doesn't work

### ISSUE THREAD

**Issue by pandabear41** [ScreepsOCS/screeps.behaviour-action-pattern#710]
My creeps will attack enemy creeps, friends within the whitelist, and even my own creeps.
This only happened after of the task.repuatition.

See this:
http://screeps.com/s/cRmmJx

**Comment by karlthepagan** [comment]
I'll get to this today.

**Comment by karlthepagan** [comment]
What is the output of these commands @pandabear41 ?

```
Task.reputation.isAlly('cyberblast')
Task.reputation.isAlly(_.find(Game.spawns,'my').owner.username)
Task.reputation.score('cyberblast')
Task.reputation.isHostile('cyberblast')
```

expected:
```
true
true
200
false
```

Go into a friendly room and check the contents of Game.rooms[coords].hostiles - this should be empty.

The hostiles and casualty list are the only way we differentiate valid targets. If there's any combat actions which don't use those then it won't be affected by reputation.

**Comment by pandabear41** [comment]
They have the same expected output. 
```
true
true
200
false
```

I see why they were attacking users in my whitelist. 
Old code had case insensitive checks, new code checks for case sensitive. 

Also I see why my creeps were attacking each other. The invading action looks at `creep.data.target`, and if I manually assigned it a travel action to another one of my creeps and then manually assigned it the invading action on current room, then it would attack the creep that was still in `creep.data.taget`. 
Line 54 in creep.action.invading
```
        if( target )
            return target;
```

**Comment by karlthepagan** [comment]
I will make reputation case-insensitive.

I thought that assigning a new action would clear the contents of creep.data.target, but I'll double-check.

**Comment by karlthepagan** [comment]
I have observed a temporary problem with the hostiles list. For a few ticks DirtyLittleCodeMonkey was at the default, and attacked. I have him configured to have a reputation score of 1 - https://screeps.com/a/#!/history/E76S9?t=17390347

**Comment by karlthepagan** [comment]
@pandabear41 please confirm that this has been resolved in 0.6.1 and in current dev. :)

**Comment by Dasku** [comment]
Is this fixed now? can we close?

**Comment by chobobobo** [comment]
Closing, assumed resolved, please reopen if you test and it is still an issue.
