### ISSUE TITLE
Robbers Repairing in Target Room

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#733]
Robbers should not repair in the target room, or any room unowned by the player.

**Comment by Dasku** [comment]
It's not an assigned action for a robber so it must be via the repair on drive by.

Maybe we can add a check to see if the room is owned by someone else?

Side note: if there is a lot of swamp in a room, you may want to repair the roads until you have finished robbing.

**Comment by Dasku** [comment]
Maybe a simple fix would be to only allow repair on drive by range 0 in non-owned or non-reserved rooms? This would allow repairing roads but not walls/ramparts.

**Comment by karlthepagan** [comment]
Build/repair on drive by is the quickest way to build roads in a non-controller room. Very important for highways and center nine.

**Comment by chobobobo** [comment]
Yeah, having the same, the trick is that we may want to repair our allies rooms, so it would need to check if the room is not ours, has an owner and the owner is not an ally.

!room.my && room.owner && !Task.reputation.isAlly(roomName)

**Comment by chobobobo** [comment]
see #935

**Comment by Spedwards** [comment]
Resolved.
