### ISSUE TITLE
Mineral Miner Haulers

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#747]
Not a bug but more of a problem. Currently if your mineral isn't close to your main area, haulers will take too long to get there and the mineral miner will eventually start dropping the mineral. Then haulers prioritise this instead of their current job, wasting time to pick up 100-odd of the mineral, and not touching the containers full of the mineral.

I have an Ultra dense Oxygen in my room, and as of this issue, I have lost 28k Oxygen, presumably due to decay.

I propose perhaps a hauler dedicated to the mineral when the distance is greater than _x_.

**Comment by OverlordQ** [comment]
PR#755 should address this

**Comment by Spedwards** [comment]
It does @OverlordQ. Thanks.
