### ISSUE TITLE
Increase Room Hauler Count when Mineral Active

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#764]
When your room mineral is active, the room's hauler count should be increased by 1.

**Comment by Dasku** [comment]
Could we temporarily  fix this in the setup for max count? (assuming the setup queue wont be around for too much longer)

setup.maxCount = function(room){ 
15     if( !room.population ) return 0; 
16     let count = 0; 
17     let miners = ((room.population.typeCount['miner'] + room.population.typeCount['mineralMiner'])||0); 
18     let workers = (room.population.typeCount['worker']||0);

**Comment by Dasku** [comment]
Karl merged this
