### ISSUE TITLE
Lab Technician (Labs task)

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#800]
Discussed a bit in slack about moving the lab stuff into a task to keep it organised and clear. 

This would also allow us to spawn lab technicians when labs are active - essentially a hauler dedicated to reallocation as priority to keep everything running smoothly.

**Comment by Dasku** [comment]
If we want to use recyclers to move minerals between rooms instead of terminals it could be managed from here too. (or just reallocating to the terminal to fullfil orders)

**Comment by logxen** [comment]
I realized that moving mineral with the recyclers still doesn't work because there's no lab at the destination. One would actually have to send a pre-boosted remoteUpgrader with extra move parts.

**Comment by Dasku** [comment]
Good point for boosting. I was thinking more for just moving minerals around between rooms once a storage is in place to prepare and start using labs at RCL 6.

**Comment by logxen** [comment]
a room below 6 has no minerals nor need for minerals ... a room that's 6 has a terminal

**Comment by Dasku** [comment]
I guess its architecture question for Karl RE what goes in the task and what goes in Room etc. All the tasks we have so far are very creep focused and this is pretty different.

**Comment by logxen** [comment]
I think a lot of it actually belongs in action.reallocating where it is. Some of the functions need to be available outside the action though.

I think most of the stuff I have attached to the room is pretty good where it is.

So the task would just govern the new lab technicians? That makes sense. I'll note that the current implementation of action.reallocating can only be used by one creep at a time. Even if one raised the number at the top of action.reallocating they wouldn't behave intelligently without upgrading the whole system ... they would all try to do the same job. This will probably be easier to do once I've refactored it some and made the logic easier to see.

**Comment by Dasku** [comment]
Other jobs for lab tech: (probably via reallocating)
- Filling labs with minerals
- Filling labs with energy
- Resetting labs for boosting (advanced tactic, internal)
- Filling nuker with energy & GO
- Filling powerSpawn with energy & power 
- Filling/providing terminal orders

**Comment by Dasku** [comment]
I've made a very simple task for labTech to spawn a hauler with overridden priorities to pick reallocating first. (branch https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/tree/task/labTech )

Quite a few PR's atm so I'll wait to pull it but its there is anyone wants it.

**Comment by Dasku** [comment]
Pretty much implemented now - manage from PR - new issues for improvements
