### ISSUE TITLE
Stop Spawning Non-Critical Roles when Bucket <= CRITICAL_BUCKET_LEVEL * 2/3

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#818]
Currently well below `CRITICAL_BUCKET_LEVEL`, working on up, but my spawns are working on non-critical roles instead of critical ones that are needed to stay afloat.

While `Game.cpu.bucket <= CRITICAL_BUCKET_LEVEL * 2/3` spawns should skip over non-critical roles.

**Comment by chobobobo** [comment]
Just got hit badly by this, remoteHaulers stinking up my base and nearly killed it because the haulers couldn't get to the extensions anymore
