### ISSUE TITLE
Spawn Small Workers for Recovering Rooms

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#841]
An emergency worker spawns, but after that minimum weight goes back to normal. That one emergency worker is barely enough to sustain itself.

The room should spawn more smaller workers as if it's a low RCL room.

**Comment by Dasku** [comment]
Still getting gimp workers in every RCL8 room stopping fortifying etc.

**Comment by Spedwards** [comment]
This seems to be resolved. I've had a lot of collapses (due to unrelated bug) and the code recovered nicely.
