### ISSUE TITLE
Potential Crazy Idea For Bucket Fix

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#843]
Do note this would be a short-term fix over a long period of time. It's crazy but theoretically would work.

So `CRITICAL_BUCKET_LEVEL` helps stabilise your bucket around that level, so theoretically, slowly raising that level would also mean that your bucket would slowly raise. Once your critical bucket level has reached a certain threshold, somewhere around 9.5k, it should return to your base level.

Again, crazy, but theoretically would have some improvement.

**Comment by chobobobo** [comment]
I can see how raising that level would slowly increase the bucket by forcing execution to hit that limit, however I fail to see the benefit of raising the bucket as once it returns to the base level the bucket would slowly drain again.

**Comment by Dasku** [comment]
We happy with the current bucket critical management? can we close this?

**Comment by chobobobo** [comment]
It's great, it basically morphed into stop remote hauling creeps in practical usage but it works.

**Comment by Spedwards** [comment]
Resolved.
