### ISSUE TITLE
Nuker Defense (idea)

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#873]
When the code detects there is a nuker coming it puts ramparts around the dropping area for the creeps to build. Then the creeps prioritize it to make the ramparts have high hit points, so then the nuker does not do any damage to the structures around it.

**Comment by SEATURTLEKING** [comment]
If it is not possible to build or make the ramparts have high hit points there can be a backup code to evacuate the creeps and energy to a different room that will not be hit by a nuker.

**Comment by karlthepagan** [comment]
OCS does not generally solve end-game / military problems in the public codebase.

See these docs for how to implement personal modifications that merge easily with the OCS code https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/wiki/Custom-Module-Overrides

Let us know if you have a problem implementing this as a viral action or ideas for how to improve the framework to make this better.
