### ISSUE TITLE
Safe Mode When Spawn Is Not Spawning

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#874]
If the spawn is not spawning creeps for a number of ticks due to an issue of some sort, my idea is for the code to activate safe mode automatically. You can put it in parameters so if the player does not want it they can put it to false.

**Comment by torin555** [comment]
There's really no reason to ever put a room in automatic safe mode that wouldn't fall under #878
