### ISSUE TITLE
New Type of Dismantler

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#901]
When you are RCL 6-8 maybe you can have a special type of creep that goes to a room and destroys the road and walls etc. by taking the energy from them.

**Comment by Spedwards** [comment]
This could be worked from Dismantlers most probably.

**Comment by SEATURTLEKING** [comment]
ya i just got attacked by one and i had to restart my new room

**Comment by Dasku** [comment]
you could use privateers for this purpose?

I think train solves this issue internally.
