### ISSUE TITLE
Yellow/Yellow defence flags not working

### ISSUE THREAD

**Issue by xXtheguy52Xx** [ScreepsOCS/screeps.behaviour-action-pattern#907]
the memory leaves this on the master build {"tasks":{"guard":{"queued":[],"spawning":[],"running":[]}}}

**Comment by karlthepagan** [comment]
what is the git branch & hash or name & date of the zip file you're using?

I have yellow/yellow flags at these rooms:
* E75S5 - 2 flags
* E75S7 - 1 flag
* E85S13 - 1 flag

**Comment by xXtheguy52Xx** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/archive/master.zip this zip as of march 2nd
