### ISSUE TITLE
(canary) Heal doesnt work

### ISSUE THREAD

**Issue by Dasku** [ScreepsOCS/screeps.behaviour-action-pattern#909]
![image](https://cloud.githubusercontent.com/assets/22677773/23578313/05c5f188-00cc-11e7-88d3-c6fe11315331.png)

I have 9 defenders spawned in this room and they are just stood waiting for the towers to heal them up, they call for healing and don't heal themselves or each other. 

![image](https://cloud.githubusercontent.com/assets/22677773/23578320/256985fe-00cc-11e7-8e49-03eb9b062a56.png)

**Comment by Dasku** [comment]
Still don't think this is working with current canary

**Comment by karlthepagan** [comment]
The creeps with (+) above their heads are not executing their regular role. They will be executing fleeMove. At one point I was playing with adding heal to the fleeMove routine but this will be CPU intensive.

**Comment by Dasku** [comment]
Well the invader it was fleeing from was about 30 squares away, can we not limit the distance it fleeMove's so it will stop and heal?

**Comment by chobobobo** [comment]
https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/836 implemented healing while fleeing, I believe this issue has now been resolved.
