### ISSUE TITLE
Defense Against A Nuker

### ISSUE THREAD

**Issue by SEATURTLEKING** [ScreepsOCS/screeps.behaviour-action-pattern#916]
When the code detects there is a nuker coming it puts ramparts around the dropping area for the creeps to build. Then the creeps prioritize it to make the ramparts have high hit points, so then the nuker does not do any damage to the structures around it. Otherwise you will probably die.

**Comment by Dasku** [comment]
You have 48 hours, in order to max ramparts would take too long and require too much energy. I think the most efficient thing to do is just dismantle the structures which will be hit

**Comment by SEATURTLEKING** [comment]
ya

**Comment by logxen** [comment]
hmmm ... 100 hits repair per energy is going to take 50k energy to get to 5M hits. 50k is not unreasonable for a few key structures.

structures that cost more than 50k might be worth protecting and anything less than that should be moved. offhand I think that's just terminal, nuker, and powerspawn? storage might be worth it if there's nowhere to move the resources to ...

**Comment by SEATURTLEKING** [comment]
or if the storage has 150k mineral or 1mill energy

**Comment by logxen** [comment]
in most cases 2 days should be more than enough time to have the storage emptied into the terminal and sent to another room.

also, this discussion should probably be moved internal.

**Comment by SEATURTLEKING** [comment]
ya
