### ISSUE TITLE
Add to Hostile Rooms Inconsistent (Traveler)

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#922]
Currently the system is `Memory.rooms.hostileRooms[roomName] = true`. To be more consistent, it should be `Memory.rooms[roomName].hostile = true`.

**Comment by chobobobo** [comment]
This is currently a limitation brought about by the way traveler is written, but since we are already using our internal room information (Task.reputation) to check allies, I think we could move the setting & checking of hostileRooms into an overridable option.

**Comment by chobobobo** [comment]
@karlthepagan I think the fix for this is to change hostileRooms into a callback, and then add .hostile to our room.js.  Each time I write Memory.rooms.hostileRooms[roomName]=false I hurt a little more inside.

**Comment by chobobobo** [comment]
Resolved in #751
