### ISSUE TITLE
Swap Spawn and Extensions in Construction Priority

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#928]
Currently the default first two structures in the list of priorities are Spawn, followed by Extensions. In my opinion, these two should be swapped.

For your first spawn, it's unlikely that you'll have extensions ready before it's done, and for all following spawns, it's probably better to build extensions first, so you spawn larger creeps, decreasing CPU usage and decreasing the time it would take to build said spawn.

Let me know what you think. If there's an agreement, we could change this.

**Comment by Dasku** [comment]
I agree post RCL2, however in most cases your pioneer will get RCL2 before it starts to do construction sites so this would lead him to do the extensions before the first spawn?

**Comment by logxen** [comment]
honestly i'm not sure I'd mind that ... stupid useless 200 energy workers anyway. just let the pioneer do his job. :)

**Comment by logxen** [comment]
would have to make sure it didn't lead to early room collapses I guess

**Comment by chobobobo** [comment]
this is something that could easily be added to a viral.parameters though, and not everyone would necessarily understand the value..  I'm going to add it to my viral.parameters now for sure though.

**Comment by karlthepagan** [comment]
I think it's fine to make specialized logic for the first spawn only to be prioritized first, but the default is much easier to understand.
