### ISSUE TITLE
build container next to sources so miners can deposit to them

### ISSUE THREAD

**Issue by mikiones** [ScreepsOCS/screeps.behaviour-action-pattern#94]
haulers, workers pick it up

**Comment by mikiones** [comment]
not sure what should be a trigger for action, just missing container (or construction site for one) once we have miner 1 block away?

**Comment by cyberblast** [comment]
miners get a dedicated source assigned only once and it will be stored to memory. Thats a good moment to check if there is a container at the assigned source present...

**Comment by Dasku** [comment]
This currently works already doesn't it? I have a container by both sources and mineral. 

Can this be closed?

**Comment by cyberblast** [comment]
no, its meant to be build automatically
