### ISSUE TITLE
removing remote mining flag

### ISSUE THREAD

**Issue by chobobobo** [ScreepsOCS/screeps.behaviour-action-pattern#972]
When you remove a remote mining flag it leaves its creeps in the spawn queue, it should remove those.

Also, when a creep spawns without a flag it currently gives 'creep with no action' errors, the creep should recycle (or find another remote room to service, but that's more work)

**Comment by karlthepagan** [comment]
logging spam should be eliminated at minimum for 0.7.0

**Comment by chobobobo** [comment]
resolved by https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/1258
