### ISSUE TITLE
Tower visual 

### ISSUE THREAD

**Issue by Perrytheplatypus43** [ScreepsOCS/screeps.behaviour-action-pattern#973]
Visual that tells you how much energy the tower has.

**Comment by Perrytheplatypus43** [comment]
I am working on this feature. I am still testing it. So far it's just errors.

**Comment by Spedwards** [comment]
Work on dev. Create a PR for it and I can review and help you out, since the Visuals seem to be my department 😛

**Comment by Spedwards** [comment]
Tower visuals merged.
