### ISSUE TITLE
Cannot Build New Spawn While Construction Site Exists

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#978]
While an enemy construction site for a spawn is in a room, you cannot place your own. The pioneer needs to walk over the construction site as a top priority.

**Comment by DasBrain** [comment]
Same applies if there is already an enemy spawn. (e.g. new player with no code)

**Comment by Spedwards** [comment]
@DasBrain If there is already an enemy spawn, you can destroy it. Unfortunately you cannot remove hostile construction sites.

**Comment by SEATURTLEKING** [comment]
can't you just remove the construction site yourself
but if you can't that is a big problem

**Comment by Spedwards** [comment]
@SEATURTLEKING No. You can remove structures but not construction sites.

**Comment by Spedwards** [comment]
Resolved with Bulldozing action
