### ISSUE TITLE
Traveler Pathing Around Creeps

### ISSUE THREAD

**Issue by Spedwards** [ScreepsOCS/screeps.behaviour-action-pattern#991]
Our previous method didn't do this. Pathing around isn't necessary. The creeps can just swap places. Having them path around could potentially cause issues.

Probably wouldn't have ever noticed if I didn't re-enable visuals.

**Comment by chobobobo** [comment]
@Spedwards could you clarify when this is happening and with what creeps?  As I understand, they should be ignoring creeps for initial paths (unless a specific creep type) and then only pathing around if they are "stuck" for more than a given number of ticks.

**Comment by karlthepagan** [comment]
Old pathfinder was similar to the current behavior but I can look into instrumenting a way to improve stuck detection and more efficient repathing.

**Comment by chobobobo** [comment]
After speaking with @Spedwards he added:
```I'm not 100% sure exactly. All I remember is seeing two creeps walking down the same road, going different directions, and one of the creeps walking around the other.
IIRC, one was fatigued and the other wasn't, so the next tick, the one that wasn't fatigued pathed around the other, when they could have swapped positions.
```

**Comment by chobobobo** [comment]
unclear what happened exactly
